// GENERATED by build.js from toolkit/ — do not edit by hand.
// Canonical source: toolkit/core + toolkit/adapters/chrome/librarian.entry.js
(() => {
  // ../toolkit/core/ability-model.js
  var ABILITY_MODEL_VERSION = 1;
  var WEB_LINE_HEIGHT_MIN = 1;
  var WEB_LINE_HEIGHT_MAX = 3;
  var WEB_LETTER_SPACING_MAX = 0.5;
  function letterSpacingToModel(em) {
    return 1 + em / 0.12 * 0.5;
  }
  function emptyAbilityModel() {
    return {
      schemaVersion: ABILITY_MODEL_VERSION,
      supportAreas: [],
      freeText: "",
      text: {
        size: 1,
        // relative multiplier (0.5–2.0)
        lineSpacing: 1,
        // relative multiplier (1.0 = typical)
        letterSpacing: 1,
        // relative multiplier (1.0 = typical)
        font: "standard"
        // 'standard' | 'dyslexia-friendly'
      },
      vision: {
        contrast: "standard",
        // 'standard' | 'high' (device-independent)
        contrastStyle: null,
        // the specific high-contrast variant, when known ('light' | 'yellow-black') — preserved so the web polarity round-trips
        lightPreference: "standard",
        // 'standard' | 'dark'
        colorVision: "typical",
        // 'typical' | 'protanopia' | 'deuteranopia' | 'tritanopia'
        descriptions: false
        // needs described visuals (images, video)
      },
      motion: "standard",
      // 'standard' | 'reduced'
      audio: {
        captions: false,
        // needs visual alternative to audio
        speechRate: 1
        // TTS rate multiplier
      },
      input: {
        pointer: "standard",
        // 'standard' | 'large-target'
        keyboard: false,
        // relies on keyboard navigation
        voice: false
        // relies on voice control
      },
      cognition: {
        simplify: false,
        // simpler language helps
        summarize: false,
        // summaries of long content help
        focusSupport: false,
        // reduced distraction helps
        progressCues: null,
        // true = wants them, false = avoid (sensory), null = no signal
        language: "standard"
        // 'standard' | 'plain'
      },
      confidence: {},
      // dimension path → 0..1
      derivedAt: null,
      sources: []
      // provenance: 'profile' | 'settings' | 'memory'
    };
  }
  var BOOLEAN_MAP = [
    ["dyslexiaFont", (m) => {
      m.text.font = "dyslexia-friendly";
    }, "text.font"],
    ["darkMode", (m) => {
      m.vision.lightPreference = "dark";
    }, "vision.lightPreference"],
    ["autoDescribe", (m) => {
      m.vision.descriptions = true;
    }, "vision.descriptions"],
    ["autoVideoDescribe", (m) => {
      m.vision.descriptions = true;
    }, "vision.descriptions"],
    ["motionReducer", (m) => {
      m.motion = "reduced";
    }, "motion"],
    ["autoCaptions", (m) => {
      m.audio.captions = true;
    }, "audio.captions"],
    ["largeCursor", (m) => {
      m.input.pointer = "large-target";
    }, "input.pointer"],
    ["keyboardNav", (m) => {
      m.input.keyboard = true;
    }, "input.keyboard"],
    ["voiceCommands", (m) => {
      m.input.voice = true;
    }, "input.voice"],
    ["autoSimplify", (m) => {
      m.cognition.simplify = true;
      m.cognition.language = "plain";
    }, "cognition.simplify"],
    ["autoSummarize", (m) => {
      m.cognition.summarize = true;
    }, "cognition.summarize"],
    ["focusMode", (m) => {
      m.cognition.focusSupport = true;
    }, "cognition.focusSupport"],
    ["hideDistractions", (m) => {
      m.cognition.focusSupport = true;
    }, "cognition.focusSupport"]
  ];
  function deriveAbilityModel(profile = {}, settings = {}, opts = {}) {
    const m = emptyAbilityModel();
    m.supportAreas = profile.supportAreas || [];
    m.freeText = profile.freeText || "";
    m.derivedAt = opts.now ?? null;
    const conf = (path, value, source) => {
      m.confidence[path] = Math.max(m.confidence[path] || 0, value);
      if (!m.sources.includes(source)) m.sources.push(source);
    };
    if (m.supportAreas.length || m.freeText) conf("supportAreas", 0.8, "profile");
    if (profile.metaPreferences?.language === "plain") {
      m.cognition.language = "plain";
      conf("cognition.language", 0.9, "profile");
    }
    if (typeof settings.fontScale === "number" && settings.fontScale !== 100) {
      m.text.size = clamp(settings.fontScale / 100, 0.5, 2);
      conf("text.size", 0.9, "settings");
    }
    if (typeof settings.lineHeight === "number" && settings.lineHeight !== 1.5) {
      m.text.lineSpacing = clamp(settings.lineHeight / 1.5, WEB_LINE_HEIGHT_MIN / 1.5, WEB_LINE_HEIGHT_MAX / 1.5);
      conf("text.lineSpacing", 0.9, "settings");
    }
    if (typeof settings.letterSpacing === "number" && settings.letterSpacing > 0) {
      m.text.letterSpacing = clamp(1 + settings.letterSpacing / 0.12 * 0.5, 1, letterSpacingToModel(WEB_LETTER_SPACING_MAX));
      conf("text.letterSpacing", 0.9, "settings");
    }
    if (settings.contrastMode && settings.contrastMode !== "none") {
      m.vision.contrast = "high";
      m.vision.contrastStyle = settings.contrastMode;
      conf("vision.contrast", 0.9, "settings");
    }
    const colorFilter = settings.colorFilter || settings.colorBlindMode;
    if (colorFilter && colorFilter !== "none") {
      m.vision.colorVision = colorFilter;
      conf("vision.colorVision", 0.9, "settings");
    }
    if (typeof settings.speechRate === "number" && settings.speechRate !== 1) {
      m.audio.speechRate = clamp(settings.speechRate, 0.5, 2);
      conf("audio.speechRate", 0.9, "settings");
    }
    if (settings.showProgress === true) m.cognition.progressCues = true;
    if (settings.showProgress === false) m.cognition.progressCues = false;
    for (const [key, apply, path] of BOOLEAN_MAP) {
      if (settings[key] === true) {
        apply(m);
        conf(path, 0.9, "settings");
      }
    }
    return m;
  }
  function clamp(v, min, max) {
    return Math.min(max, Math.max(min, v));
  }

  // ../toolkit/core/skill.js
  var FRONTMATTER_RE = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/;
  function parseFrontmatter(text) {
    const out = {};
    for (const line of text.split("\n")) {
      const m = line.match(/^([a-zA-Z][\w-]*):\s*(.*)$/);
      if (!m) continue;
      const key = m[1];
      let val = m[2].trim();
      if (val.startsWith("[") && val.endsWith("]")) {
        val = val.slice(1, -1).split(",").map((s) => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
      } else {
        val = val.replace(/^["']|["']$/g, "");
      }
      out[key] = val;
    }
    return out;
  }
  function extractRecipe(body) {
    const m = body.match(/```json\s*([\s\S]*?)```/);
    if (!m) return { adapters: [], actions: [] };
    try {
      const parsed = JSON.parse(m[1]);
      return {
        adapters: Array.isArray(parsed.adapters) ? parsed.adapters : [],
        actions: Array.isArray(parsed.actions) ? parsed.actions : []
      };
    } catch {
      return { adapters: [], actions: [] };
    }
  }
  function parseSkill(markdown) {
    let src = String(markdown || "").replace(/\r\n?/g, "\n");
    const lines = src.split("\n");
    const fmStart = lines.findIndex((l, i) => l.trim() === "---" && /^\s*[a-zA-Z][\w-]*\s*:/.test(lines[i + 1] || ""));
    if (fmStart > 0) src = lines.slice(fmStart).join("\n");
    const fm = src.match(FRONTMATTER_RE);
    const front = fm ? parseFrontmatter(fm[1]) : {};
    const body = fm ? fm[2].trim() : src.trim();
    const asArray = (v) => Array.isArray(v) ? v : v ? [v] : [];
    return {
      name: front.name || "",
      description: front.description || "",
      supportAreas: asArray(front.supportAreas),
      siteRelevance: asArray(front.siteRelevance),
      recipe: extractRecipe(body),
      body
    };
  }
  function serializeSkill(skill) {
    const list = (a) => `[${(a || []).join(", ")}]`;
    const front = [
      "---",
      `name: ${skill.name}`,
      `description: ${skill.description}`,
      `supportAreas: ${list(skill.supportAreas)}`,
      `siteRelevance: ${list(skill.siteRelevance)}`,
      "---"
    ].join("\n");
    let body = skill.body || "";
    if (!/```json/.test(body)) {
      body = `${body}

## Recipe
\`\`\`json
${JSON.stringify(skill.recipe || { adapters: [] }, null, 2)}
\`\`\`
`;
    }
    return `${front}

${body.trim()}
`;
  }
  function validateSkill(skill, { tools } = {}) {
    const errors = [];
    if (!skill.name) errors.push("missing name");
    if (!skill.description) errors.push("missing description");
    const steps = skill.recipe?.adapters || [];
    const actions = skill.recipe?.actions || [];
    if (steps.length === 0 && actions.length === 0) errors.push("recipe has no adapters or actions");
    for (const act of actions) {
      if (!act || typeof act.prompt !== "string" || !act.prompt.trim()) errors.push("recipe action missing prompt");
    }
    const meta = tools?.settingsMeta || {};
    for (const step of steps) {
      if (!step || typeof step.id !== "string") {
        errors.push("recipe step missing adapter id");
        continue;
      }
      if (tools?.byId && !tools.byId(step.id)) errors.push(`unknown adapter "${step.id}"`);
      for (const [key, val] of Object.entries(step.settings || {})) {
        const m = meta[key];
        if (Object.keys(meta).length && !m) {
          errors.push(`unknown setting "${key}" in adapter "${step.id}"`);
          continue;
        }
        if (!m) continue;
        if (m.type === "number") {
          if (typeof val !== "number" || Number.isNaN(val)) errors.push(`setting "${key}" must be a number`);
          else if (Array.isArray(m.range) && (val < m.range[0] || val > m.range[1])) errors.push(`setting "${key}"=${val} out of range ${m.range[0]}\u2013${m.range[1]}`);
        } else if (m.type === "boolean" && typeof val !== "boolean") {
          errors.push(`setting "${key}" must be true or false`);
        } else if (m.type === "enum" && Array.isArray(m.options) && !m.options.includes(val)) {
          errors.push(`setting "${key}"="${val}" not one of ${m.options.join(", ")}`);
        }
      }
    }
    return { valid: errors.length === 0, errors };
  }
  function resolveSkill(skill) {
    const settings = {};
    const adapterIds = [];
    for (const step of skill.recipe?.adapters || []) {
      if (!step?.id) continue;
      adapterIds.push(step.id);
      Object.assign(settings, step.settings || {});
    }
    const actions = (skill.recipe?.actions || []).filter((a) => a && typeof a.prompt === "string" && a.prompt.trim()).map((a) => ({ name: a.name || a.prompt, prompt: a.prompt }));
    return { settings, adapterIds, actions };
  }
  function matchSkill(skill, { supportAreas = [], category = null } = {}) {
    let score = 0;
    const areas = new Set(supportAreas);
    for (const a of skill.supportAreas || []) if (areas.has(a)) score += 2;
    const rel = skill.siteRelevance || [];
    if (category && rel.includes(category)) score += 3;
    if (rel.includes("all")) score += 1;
    return score;
  }
  var GENERIC_WORDS = /* @__PURE__ */ new Set([
    "the",
    "and",
    "for",
    "with",
    "when",
    "that",
    "this",
    "them",
    "they",
    "have",
    "from",
    "make",
    "making",
    "want",
    "need",
    "please",
    "help",
    "like",
    "can",
    "could",
    "would",
    "site",
    "page",
    "website",
    "web",
    "get",
    "turn",
    "use",
    "using",
    "more",
    "some",
    "all",
    "every",
    "thing"
  ]);
  function needTokens(text) {
    return String(text || "").toLowerCase().split(/[^a-z0-9]+/).map((w) => w.length > 3 && w.endsWith("s") && !w.endsWith("ss") ? w.slice(0, -1) : w).filter((w) => w.length > 2 && !GENERIC_WORDS.has(w));
  }
  function tokenLike(a, b) {
    if (a === b) return true;
    const [short, long] = a.length <= b.length ? [a, b] : [b, a];
    return short.length >= 4 && long.startsWith(short);
  }
  function matchSkillToNeed(skill, need) {
    const needToks = [...new Set(needTokens(need))];
    if (!needToks.length) return 0;
    const fields = [
      { toks: needTokens(skill.name), weight: 3 },
      { toks: needTokens((skill.supportAreas || []).join(" ")), weight: 2 },
      { toks: needTokens((skill.siteRelevance || []).join(" ")), weight: 2 },
      { toks: needTokens(skill.description), weight: 2 }
    ];
    let score = 0;
    for (const t of needToks) {
      let best = 0;
      for (const f of fields) {
        if (f.weight > best && f.toks.some((ft) => tokenLike(t, ft))) best = f.weight;
      }
      score += best;
    }
    return score;
  }

  // ../toolkit/core/skill-builder.js
  function buildSkillPrompt(need, { profile = {}, tools, taxonomy, previous = null, feedback = "" } = {}) {
    const adapters = tools.forPrompt().map((t) => `- ${t.id} \u2014 ${t.name}: ${t.description} (helps: ${t.supportAreas.join(", ")})`).join("\n");
    const settingsVocab = tools.settingsVocabularyLines().join("\n");
    const categories = taxonomy ? taxonomy.categoryIds().join(", ") : "news, social, video, shopping, education, productivity, reference, other";
    const profileBlock = profile.supportAreas?.length || profile.freeText ? `
About this person:
- Support areas: ${(profile.supportAreas || []).join(", ") || "unspecified"}` + (profile.freeText ? `
- In their words: "${profile.freeText}"` : "") : "";
    const revisionBlock = previous && feedback ? `

You already built this skill for that need:

${serializeSkill(previous)}

The person tried it and said: "${feedback}"
Revise the skill to address their feedback. Keep the same name unless the feedback changes what the skill is about, and keep the parts that already worked.` : "";
    return `You are the Engineer \u2014 an accessibility skill builder. Author a SKILL.md that adapts web pages for the need below by composing EXISTING adapters. You do NOT write code; you write a playbook that names which adapters to apply and with what settings.

The need: "${need}"${profileBlock}${revisionBlock}

Available adapters (use only these ids):
${adapters}

Setting keys and their units/ranges (use only these; values must be in range):
${settingsVocab}

Site categories for siteRelevance: ${categories} (or "all").

Output a COMPLETE SKILL.md, nothing else, in exactly this shape:

---
name: <short-kebab-case-id>
description: <one sentence: what it does and WHEN to use it \u2014 this is what an agent matches on>
supportAreas: [<comma-separated from the adapters' "helps" areas>]
siteRelevance: [<comma-separated categories, or "all">]
---

# <Title>

<1-2 sentences: what this skill does for the person.>

## What it does
<numbered list: each adapter you apply and why, in plain language.>

## When to use
<when it helps and when to skip it.>

## Recipe
\`\`\`json
{
  "adapters": [
    { "id": "<adapter-id>", "settings": { "<key>": <value> } }
  ]
}
\`\`\`

Rules:
- Only reference adapter ids and setting keys listed above. Keep the recipe minimal \u2014 1 to 4 adapters that directly serve the need.
- The "Recipe" JSON is the machine-runnable truth; make the prose match it.
- Prefer the narrowest siteRelevance the need implies; use "all" only for genuinely global needs.`;
  }
  function parseBuiltSkill(llmOutput, { tools } = {}) {
    let text = String(llmOutput || "").trim();
    const outer = text.match(/^```(?:markdown|md)?\s*\n([\s\S]*)\n```$/);
    if (outer) text = outer[1].trim();
    const skill = parseSkill(text);
    const { valid, errors } = validateSkill(skill, { tools });
    return { skill, valid, errors };
  }
  async function buildSkill(need, { llm, tools, taxonomy, profile, previous = null, feedback = "" } = {}) {
    if (!llm) return { skill: null, valid: false, errors: ["no LLM available"] };
    const prompt = buildSkillPrompt(need, { profile, tools, taxonomy, previous, feedback });
    let out;
    try {
      out = await llm(prompt);
    } catch (e) {
      return { skill: null, valid: false, errors: [`LLM call failed: ${e.message}`] };
    }
    return parseBuiltSkill(out, { tools });
  }

  // ../toolkit/core/librarian.js
  function createLibrarian({
    datastore,
    taxonomy,
    kv: kv2,
    clock = { now: () => Date.now() },
    notifier: notifier2 = { pending: async () => {
    } },
    demo: demo2 = { active: () => false, trace: () => {
    } }
  }) {
    const DS = datastore;
    const TAX = taxonomy;
    let _gemini = null;
    function newId(prefix) {
      return `${prefix}-${clock.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
    }
    function originOf(url) {
      try {
        return new URL(url).hostname.toLowerCase().replace(/^www\./, "");
      } catch {
        return null;
      }
    }
    function parseJsonLoose(text) {
      if (!text) return null;
      let t = String(text).trim().replace(/^```(?:json)?\s*/i, "").replace(/```\s*$/, "");
      try {
        return JSON.parse(t);
      } catch {
      }
      const m = t.match(/\{[\s\S]*\}/);
      if (m) {
        try {
          return JSON.parse(m[0]);
        } catch {
        }
      }
      return null;
    }
    const DECAY_HALF_LIFE = {
      stable: Infinity,
      slow: 1e3 * 60 * 60 * 24 * 90,
      // ~90 days
      fast: 1e3 * 60 * 60 * 24 * 7
      // ~7 days
    };
    function scoreRecord(r, now) {
      const half = DECAY_HALF_LIFE[r.decayClass] || DECAY_HALF_LIFE.slow;
      const age = now - (r.lastAccessed || r.updatedAt || r.createdAt || now);
      const recency = half === Infinity ? 1 : Math.pow(0.5, age / half);
      return recency * ((r.importance || 5) / 10) * (r.confidence ?? 0.7);
    }
    function conditionsMet(r, now) {
      if (!r.conditions) return true;
      const d = new Date(now);
      if (r.conditions.timeOfDay) {
        const h = d.getHours();
        const { fromHour = 0, toHour = 24 } = r.conditions.timeOfDay;
        const inWindow = fromHour <= toHour ? h >= fromHour && h < toHour : h >= fromHour || h < toHour;
        if (!inWindow) return false;
      }
      if (Array.isArray(r.conditions.daysOfWeek) && r.conditions.daysOfWeek.length) {
        if (!r.conditions.daysOfWeek.includes(d.getDay())) return false;
      }
      return true;
    }
    const VALID_SCOPE = /^(general|category:[a-z-]+|context:[a-z-]+|origin:[a-z0-9.-]+|tool:[a-zA-Z0-9_-]+)$/;
    const MEMORY_PREFIX = "aa.mine.memory.";
    const UNSAFE_KEYS2 = /* @__PURE__ */ new Set(["__proto__", "prototype", "constructor"]);
    function sanitizeSettings(settings) {
      if (!settings || typeof settings !== "object") return settings;
      let meta = {};
      try {
        meta = DS().global.tools().settingsMeta || {};
      } catch (_) {
      }
      const out = {};
      for (const [k, v] of Object.entries(settings)) {
        const m = meta[k];
        if (m && m.type === "number" && Array.isArray(m.range) && typeof v === "number") {
          const [min, max] = m.range;
          let val = v;
          if (val < min && val * 100 >= min && val * 100 <= max) val = val * 100;
          out[k] = Math.min(max, Math.max(min, val));
        } else {
          out[k] = v;
        }
      }
      return out;
    }
    function normalizeRecord(raw, now) {
      const r = { ...raw };
      r.id = r.id || newId("mem");
      r.text = String(r.text || "").slice(0, 500);
      r.tier = ["profile", "preference", "site", "task"].includes(r.tier) ? r.tier : "preference";
      r.scope = VALID_SCOPE.test(r.scope || "") ? r.scope : "general";
      r.kind = ["preference", "procedural", "suppression", "rule", "observation"].includes(r.kind) ? r.kind : "preference";
      r.importance = Math.min(10, Math.max(1, Number(r.importance) || 5));
      r.confidence = Math.min(1, Math.max(0, Number(r.confidence ?? 0.7)));
      r.decayClass = ["stable", "slow", "fast"].includes(r.decayClass) ? r.decayClass : "slow";
      r.conditions = r.conditions || null;
      r.settings = r.settings && typeof r.settings === "object" ? sanitizeSettings(r.settings) : null;
      r.aspect = r.aspect || null;
      r.occurrenceCount = Math.max(1, Number(r.occurrenceCount) || 1);
      r.firstSeenAt = r.firstSeenAt || now;
      r.createdAt = r.createdAt || now;
      r.updatedAt = now;
      r.lastAccessed = r.lastAccessed || now;
      r.status = ["active", "superseded", "expired"].includes(r.status) ? r.status : "active";
      r.supersededBy = r.supersededBy || null;
      r.source = r.source || "inferred";
      r.evidence = Array.isArray(r.evidence) ? r.evidence.slice(0, 20) : [];
      return r;
    }
    function scopesFor(url, contexts) {
      const scopes = ["general"];
      for (const c of contexts || []) {
        if (TAX().contexts.some((x) => x.id === c)) scopes.push(`context:${c}`);
      }
      const origin = originOf(url);
      return { scopes, origin };
    }
    async function loadScopeShards(url, contexts) {
      const { scopes, origin } = scopesFor(url, contexts);
      let category = null;
      if (origin) {
        category = await Librarian.getSiteCategory(origin);
        if (category) scopes.splice(scopes.length, 0, `category:${category}`);
        scopes.push(`origin:${origin}`);
      }
      const shards = {};
      for (const s of scopes) shards[s] = await DS().getMemoryShard(s);
      return { scopes, shards, origin, category };
    }
    const PROFILE_DEFAULTS = {
      schemaVersion: 1,
      supportAreas: [],
      freeText: "",
      fields: {},
      // canonical ability fields, e.g. { vision: { fontScale: 130 } }
      metaPreferences: {
        consentBoundary: "profile-only",
        // 'profile-only' | 'all-tiers'
        language: "standard",
        // 'standard' | 'plain'
        maxProposalsPerWeek: 30,
        sharing: "personal"
        // 'personal' | 'friends' | 'anyone' — the
        // broker's export ceiling (privacy layer)
      },
      memoryPaused: false
    };
    async function getOrInitProfile() {
      let p = await DS().get("mine.profile");
      if (!p) {
        const legacy = await DS().get("mine.onboardingProfile");
        p = structuredClone(PROFILE_DEFAULTS);
        if (legacy) {
          p.supportAreas = legacy.supportAreas || [];
          p.freeText = legacy.freeText || "";
        }
        p.createdAt = clock.now();
        p.updatedAt = clock.now();
        await DS().set("mine.profile", p);
      }
      return p;
    }
    const Librarian = {
      setGeminiCaller(fn) {
        _gemini = fn;
      },
      // ====================== FAST LANE (no LLM) ======================
      async getProfile() {
        return await getOrInitProfile();
      },
      // The modality-agnostic AbilityModel (Phase 1): profile understanding +
      // the person's general-scope effective settings, expressed in
      // device-independent terms. Surfaces render it per-device — see
      // toolkit/surfaces/web.js and toolkit/surfaces/xr.js.
      async getAbilityModel() {
        const profile = await getOrInitProfile();
        const { settings } = await this.getEffectivePreferences(null, []);
        return deriveAbilityModel(profile, settings, { now: clock.now() });
      },
      // User-initiated edit — bypasses the proposal gate by design (the gate
      // exists for *inferred* changes; explicit user intent needs no consent).
      async setProfileField(path, value) {
        const parts = String(path).split(".");
        if (parts.some((seg) => UNSAFE_KEYS2.has(seg))) {
          throw new Error(`Librarian: refusing unsafe profile path "${path}"`);
        }
        return await DS().patch("mine.profile", async (p) => {
          p = p || structuredClone(PROFILE_DEFAULTS);
          let obj = p;
          for (let i = 0; i < parts.length - 1; i++) {
            if (typeof obj[parts[i]] !== "object" || obj[parts[i]] == null) obj[parts[i]] = {};
            obj = obj[parts[i]];
          }
          obj[parts[parts.length - 1]] = value;
          p.updatedAt = clock.now();
          return p;
        });
      },
      // Fast lane for manual setting flips (popup toggle, onboarding choice).
      // A deliberate change is the strongest preference signal there is, so it
      // is recorded immediately as a durable user-explicit record that gets
      // FINAL say in getEffectivePreferences — without this, an auto-apply
      // profile or a learned record re-imposes the old value on the next page
      // and the user's change silently "doesn't stick". One record per setting
      // key, updated in place on subsequent changes. Recorded even while
      // memory is paused: this is a direct user command, not an inference.
      async recordExplicitSetting(key, value, origin) {
        return this.recordScopedSettings("general", { [key]: value }, { origin });
      },
      // Generalized explicit-setting writer: upserts one durable user-explicit
      // record PER setting key at the given scope (general | category:<id> |
      // origin:<host> | context:<id>). These get final say in
      // getEffectivePreferences, but a scoped record only loads when the page
      // matches that scope — so "make news sites easier to read" lands on
      // category:news and does NOT leak to every site. scopeLabel is a
      // human phrase for the record text. Returns the record ids.
      async recordScopedSettings(scope, settings, opts = {}) {
        const now = clock.now();
        scope = VALID_SCOPE.test(scope || "") ? scope : "general";
        const where = opts.scopeLabel || (scope === "general" ? "" : scope.startsWith("category:") ? ` on ${scope.slice(9)} sites` : scope.startsWith("origin:") ? ` on ${scope.slice(7)}` : scope.startsWith("context:") ? ` for ${scope.slice(8)} content` : "");
        const shard = await DS().getMemoryShard(scope);
        const ids = [];
        for (const [key, value] of Object.entries(settings || {})) {
          const aspect = `setting.${key}`;
          const text = `You set ${key} to ${JSON.stringify(value)}${where}.`;
          let rec = shard.find((r) => r.source === "user-explicit" && r.aspect === aspect && r.status === "active");
          if (rec) {
            rec.settings = { [key]: value };
            rec.text = text;
            rec.occurrenceCount = (rec.occurrenceCount || 1) + 1;
            rec.updatedAt = now;
            rec.lastAccessed = now;
          } else {
            rec = normalizeRecord({
              kind: "preference",
              tier: "preference",
              scope,
              aspect,
              source: "user-explicit",
              confidence: 1,
              importance: 8,
              decayClass: "stable",
              settings: { [key]: value },
              text
            }, now);
            shard.push(rec);
          }
          ids.push(rec.id);
        }
        await DS().setMemoryShard(scope, shard);
        return ids;
      },
      // Classify once, cache forever; user override wins and is sticky.
      // Deterministic by default — pass {allowLlm: true, title} to let the
      // host's classify handler fall through to Gemini for unknown hosts.
      async getSiteCategory(origin, opts = {}) {
        origin = (origin || "").toLowerCase().replace(/^www\./, "");
        if (!origin) return null;
        const idx = await DS().get("mine.siteIndex");
        const hit = idx[origin];
        if (hit && (hit.source === "user" || hit.taxonomyVersion === TAX().version)) {
          return hit.category;
        }
        let category = TAX().categoryForHost(origin);
        let source = "hostmap";
        if (!category && opts.allowLlm && _gemini) {
          try {
            const valid = TAX().categoryIds();
            const out = await _gemini(
              `Classify this website into exactly one category. Hostname: "${origin}", Title: "${opts.title || ""}". Categories: ${valid.join(", ")}. Return ONLY the category word, nothing else.`
            );
            const cleaned = (out || "").trim().toLowerCase();
            category = valid.includes(cleaned) ? cleaned : "other";
            source = "llm";
          } catch {
            category = null;
          }
        }
        if (category) {
          await DS().patch("mine.siteIndex", (cur) => {
            cur[origin] = { category, source, classifiedAt: clock.now(), taxonomyVersion: TAX().version, ...cur[origin]?.paused ? { paused: true } : {} };
            return cur;
          });
        }
        return category;
      },
      async setSiteCategoryOverride(origin, category) {
        origin = (origin || "").toLowerCase().replace(/^www\./, "");
        await DS().patch("mine.siteIndex", (cur) => {
          cur[origin] = { ...cur[origin] || {}, category, source: "user", classifiedAt: clock.now(), taxonomyVersion: TAX().version };
          return cur;
        });
      },
      // Deterministic scope-chain merge of machine-actionable settings.
      // Order (later wins): general → context → category → explicit
      // customProfile (user-authored beats inferred at category level) →
      // origin. Rule records (kind 'rule') in a shard apply after that
      // shard's preferences. Conditions (time windows) filter throughout.
      async getEffectivePreferences(url, contexts = []) {
        const now = clock.now();
        const { scopes, shards, origin, category } = await loadScopeShards(url, contexts);
        const merged = {};
        const applied = [];
        const provenance = {};
        const assign = (src, scope) => {
          const clean = sanitizeSettings(src) || {};
          Object.assign(merged, clean);
          for (const k of Object.keys(clean)) provenance[k] = scope;
        };
        const EXPLICIT_SOURCES = /* @__PURE__ */ new Set(["user-explicit", "accepted-proposal"]);
        const explicit = [];
        const applyShard = (scope) => {
          const recs = (shards[scope] || []).filter((r) => r.status === "active" && r.settings && conditionsMet(r, now)).sort((a, b) => (a.kind === "rule") - (b.kind === "rule"));
          for (const r of recs) {
            if (EXPLICIT_SOURCES.has(r.source)) {
              explicit.push({ r, scope });
              continue;
            }
            assign(r.settings, scope);
            applied.push({ id: r.id, scope, text: r.text });
          }
        };
        for (const s of scopes) {
          if (s.startsWith("origin:")) continue;
          applyShard(s);
          if (s.startsWith("category:") && category) {
            const profiles = await DS().get("mine.profiles") || [];
            const match = profiles.find((p) => p.autoApply && p.siteTypes?.includes(category));
            if (match?.settings) {
              assign(match.settings, s);
              applied.push({ id: match.id, scope: s, text: `Profile "${match.name}"`, explicit: true });
            }
          }
        }
        if (origin) applyShard(`origin:${origin}`);
        const specificity = (sc) => sc.startsWith("origin:") ? 3 : sc.startsWith("category:") ? 2 : sc.startsWith("context:") ? 1 : 0;
        explicit.sort((a, b) => specificity(a.scope) - specificity(b.scope) || (a.r.updatedAt || 0) - (b.r.updatedAt || 0));
        for (const { r, scope } of explicit) {
          assign(r.settings, scope);
          applied.push({ id: r.id, scope, text: r.text, explicit: true });
        }
        return { settings: merged, applied, provenance, category, origin };
      },
      // Context block for agent prompts: core memory block + scored facts for
      // this page + category playbook. Deterministic; markdown at the
      // boundary, records at rest.
      async recall(url, task = "", contexts = []) {
        const now = clock.now();
        const { scopes, shards, origin, category } = await loadScopeShards(url, contexts);
        const profile = await getOrInitProfile();
        const views = await DS().get("mine.views");
        const facts = [];
        for (const s of scopes) {
          for (const r of shards[s] || []) {
            if (r.status !== "active" || r.kind === "suppression" || !conditionsMet(r, now)) continue;
            facts.push({ ...r, _scope: s, _score: scoreRecord(r, now) });
          }
        }
        facts.sort((a, b) => b._score - a._score);
        const top = facts.slice(0, 12);
        const touched = new Set(top.map((r) => r.id));
        for (const s of new Set(top.map((r) => r._scope))) {
          const shard = shards[s].map((r) => touched.has(r.id) ? { ...r, lastAccessed: now } : r);
          await DS().setMemoryShard(s, shard);
        }
        const lines = [];
        const core = views.coreBlock || `Support areas: ${profile.supportAreas.join(", ") || "not specified"}.` + (profile.freeText ? ` Notes: ${profile.freeText}` : "");
        lines.push("### About this user", core);
        const byScope = (pred, title) => {
          const hits = top.filter(pred);
          if (hits.length) {
            lines.push(`### ${title}`);
            for (const f of hits) lines.push(`- ${f.text}`);
          }
        };
        byScope((f) => f._scope === "general", "General preferences");
        byScope((f) => f._scope.startsWith("context:"), "For this kind of content");
        byScope((f) => f._scope.startsWith("category:"), category ? `On ${category} sites` : "On sites like this");
        byScope((f) => f._scope.startsWith("origin:"), origin ? `On ${origin}` : "On this site");
        const playbook = category && views.playbooks && views.playbooks[category];
        if (playbook) lines.push(`### Playbook: ${category} sites`, playbook);
        const procedural = await this.listProcedural(category);
        const actions = procedural.filter((p) => p.kind === "saved-action");
        if (actions.length) {
          lines.push("### Learned automations for sites like this");
          for (const a of actions.slice(0, 5)) lines.push(`- ${a.name}`);
        }
        return { block: lines.join("\n"), facts: top, profile, category, origin, procedural };
      },
      async listMemories(filter = {}) {
        const out = [];
        const all = await kv2.getAll();
        for (const [key, recs] of Object.entries(all)) {
          if (!key.startsWith(MEMORY_PREFIX)) continue;
          const scope = key.slice(MEMORY_PREFIX.length);
          for (const r of recs || []) {
            if (filter.status && r.status !== filter.status) continue;
            if (filter.scope && scope !== filter.scope) continue;
            out.push({ ...r, scope });
          }
        }
        const supp = await DS().get("mine.suppressions");
        return { memories: out, suppressions: supp };
      },
      async deleteMemory(id) {
        const all = await kv2.getAll();
        for (const [key, recs] of Object.entries(all)) {
          if (!key.startsWith(MEMORY_PREFIX)) continue;
          const idx = (recs || []).findIndex((r) => r.id === id);
          if (idx >= 0) {
            recs.splice(idx, 1);
            await kv2.set({ [key]: recs });
            return true;
          }
        }
        let found = false;
        await DS().patch("mine.suppressions", (s) => {
          const next = (s || []).filter((x) => x.id !== id);
          found = next.length !== (s || []).length;
          return next;
        });
        return found;
      },
      async listProposals(status = "pending") {
        const props = await DS().get("mine.proposals");
        return status ? props.filter((p) => p.status === status) : props;
      },
      // Procedural memory (Phase 2): what the person's assistant KNOWS HOW TO
      // DO for them — custom adapters (mine.skills) and saved reusable actions
      // (mine.profiles[].actions). Storage stays where it is (no migration;
      // the catalog maps it); this is the unified read surface.
      async listProcedural(category = null) {
        const out = [];
        for (const s of await DS().get("mine.skills") || []) {
          if (s.enabled === false) continue;
          const scope = s.scope || "general";
          if (category && scope.startsWith("category:") && scope.slice(9) !== category) continue;
          out.push({
            kind: "custom-adapter",
            id: s.id,
            name: s.name,
            description: s.description || "",
            scope
          });
        }
        for (const p of await DS().get("mine.profiles") || []) {
          if (!p.autoApply) continue;
          if (category && !(p.siteTypes || []).includes(category)) continue;
          for (const a of p.actions || []) {
            out.push({
              kind: "saved-action",
              id: a.id,
              name: a.name,
              prompt: a.prompt,
              siteTypes: p.siteTypes || [],
              profileId: p.id
            });
          }
        }
        return out;
      },
      // ====================== SKILLS (the Engineer + Skills db) ======================
      // All skills available to this person: built-in (global tier) + their own
      // (mine.skillDocs). Each is a parsed Skill object. This is the read side
      // of the diagrams' "Skills db".
      async listSkills() {
        const builtin = (DS().global.skills() || []).map((s) => ({ ...s, source: "builtin" }));
        const mine = (await DS().get("mine.skillDocs") || []).map((s) => ({ ...s, source: "mine" }));
        return [...builtin, ...mine];
      },
      // Retrieve the best-fitting skill for a page + this person (diagram:
      // "Librarian retrieves the skill for use"). Deterministic scoring over
      // the ability profile's support areas and the page category. Returns the
      // top match (or null), so the caller can apply it.
      async retrieveSkill(url, contexts = []) {
        const profile = await getOrInitProfile();
        const origin = originOf(url);
        const category = origin ? await this.getSiteCategory(origin) : null;
        const ctx = { supportAreas: profile.supportAreas || [], category };
        const scored = (await this.listSkills()).map((s) => ({ skill: s, score: matchSkill(s, ctx) })).filter((x) => x.score > 0).sort((a, b) => b.score - a.score);
        return scored.length ? scored[0].skill : null;
      },
      // The skill-creation flow's first diamond: "does the skill exist in the
      // db?" — checked BEFORE the Engineer builds anything. Built-in and the
      // person's own skills both count. Deterministic keyword match (no LLM),
      // so the reuse offer works without an API key. Returns the best fit or
      // null when nothing plausibly covers the need.
      async findSkillForNeed(need) {
        const scored = (await this.listSkills()).map((s) => ({ skill: s, score: matchSkillToNeed(s, need) })).filter((x) => x.score >= 4).sort((a, b) => b.score - a.score);
        return scored.length ? scored[0].skill : null;
      },
      // Compile a skill to the deterministic apply-plan (settings + adapter ids)
      // the host's adapter layer consumes. No LLM at apply-time.
      resolveSkill(skill) {
        return resolveSkill(skill);
      },
      // The Engineer: build a new skill from a plain-language need, grounded in
      // the real adapter catalog. Does NOT save — returns the skill for the
      // user to validate first (the adaptive evaluation interface). Consent
      // before persistence is the toolkit's rule. When validation fails, pass
      // the rejected attempt back as { previous, feedback } and the Engineer
      // revises it — the evaluation loop's "fail → back to the builder" arrow.
      async buildSkill(need, opts = {}) {
        const profile = await getOrInitProfile();
        return await buildSkill(need, {
          llm: _gemini,
          tools: DS().global.tools(),
          taxonomy: TAX(),
          profile,
          previous: opts.previous || null,
          feedback: opts.feedback || ""
        });
      },
      // Persist a user-validated skill to their Skills db (mine.skillDocs).
      // Re-validates against the registry so a malformed skill can't be stored.
      async saveSkill(skill) {
        const { valid, errors } = validateSkill(skill, { tools: DS().global.tools() });
        if (!valid) return { saved: false, errors };
        await DS().patch("mine.skillDocs", (skills) => {
          const idx = skills.findIndex((s) => s.name === skill.name);
          const entry = { ...skill, savedAt: clock.now() };
          if (idx >= 0) skills[idx] = entry;
          else skills.push(entry);
          return skills;
        });
        await this.logObservation({
          type: "saved-action",
          text: `Saved skill "${skill.name}" \u2014 helps with ${(skill.supportAreas || []).join(", ") || "unspecified areas"}; applies on ${(skill.siteRelevance || []).join(", ") || "all"} sites`,
          data: { skill: skill.name, supportAreas: skill.supportAreas || [], triggers: skill.siteRelevance || [] }
        }).catch(() => {
        });
        return { saved: true, errors: [] };
      },
      async deleteSkill(name) {
        let removed = false;
        await DS().patch("mine.skillDocs", (skills) => {
          const next = skills.filter((s) => s.name !== name);
          removed = next.length !== skills.length;
          return next;
        });
        return removed;
      },
      // Consent gateway for externally-sourced insights (the broker calls
      // this; nothing else writes proposals). Same suppression/cooldown/
      // weekly-cap gates as internal inferences; provenance is preserved so
      // the consent UI can say WHO is suggesting.
      async proposeInsight(draft, meta = {}) {
        const profile = await getOrInitProfile();
        const suppressions = await DS().get("mine.suppressions");
        const before = (await DS().get("mine.proposals")).filter((p) => p.status === "pending").length;
        await this._draftProposals([{
          ...draft,
          rationale: meta.source ? `[from ${meta.source}] ${draft.rationale || ""}`.trim() : draft.rationale || ""
        }], { suppressions, profile, now: clock.now() });
        const after = await DS().get("mine.proposals");
        const queued = after.filter((p) => p.status === "pending").length > before;
        if (queued && meta.source) {
          const prop = after.filter((p) => p.status === "pending" && p.aspect === draft.aspect).pop();
          if (prop) {
            prop.origin = { source: meta.source, grantId: meta.grantId || null, confidence: meta.confidence ?? null };
            await DS().set("mine.proposals", after);
          }
        }
        await updateBadge();
        return queued;
      },
      // Prompt for the popup's "what support do you need?" flow. The Librarian
      // owns it so the "does this exist in the global db?" decision is grounded
      // in the actual tools registry (Datastore.global.tools) and conditioned
      // on the ability profile — not a hand-maintained vocabulary copy.
      // Fast lane: builds a string, never calls the LLM itself.
      async interpretNeedsPrompt(text) {
        const tools = DS().global.tools();
        const profile = await getOrInitProfile();
        const profileBlock = profile.supportAreas.length || profile.freeText ? `

What we know about this user:
- Support areas: ${profile.supportAreas.join(", ") || "unspecified"}` + (profile.freeText ? `
- In their words: "${profile.freeText}"` : "") : "";
        return `You are an accessibility assistant for a browser extension. The user describes what they need in plain language. Map their description to specific extension settings.

Available settings (use these exact keys):
${tools.settingsVocabularyLines().join("\n")}

Built-in tools these settings belong to (for context on what already exists):
${tools.forPrompt().map((t) => `- ${t.name}: ${t.description}`).join("\n")}${profileBlock}

Site categories (for scoping): ${TAX().categoryIds().join(", ")}.

User says: "${text}"

Return ONLY valid JSON with:
{
  "summary": "One friendly sentence describing what you understood",
  "scope": "Where these settings should apply. Use 'general' for everywhere (the default). If the user limits it to a kind of site, use 'category:<id>' with one of the categories above (e.g. 'on news sites' -> 'category:news', 'when watching videos' -> 'category:video'). If they name a specific website, use 'origin:<hostname>' (e.g. 'on youtube.com'). Only narrow the scope when the user explicitly limits it.",
  "settings": { /* only keys that should change, with their values */ },
  "reasons": { /* same keys as settings, each with a short reason why */ },
  "newSkills": [ /* ONLY if the user's need CANNOT be fully met by the settings and built-in tools above, suggest custom skills to build. Each object has "name" (short) and "description" (1-2 sentences of what it would do). Leave as empty array [] if existing settings are sufficient. */ ]
}`;
      },
      // The single entry point for observations — and the privacy floor.
      // Drops (never logs) when globally paused, when the origin is paused,
      // or when the origin's category is a no-memory zone without an explicit
      // opt-in. The log is the pipeline's WAL: extraction consumes entries
      // behind a cursor, so a crash mid-extraction loses nothing.
      async logObservation(obs) {
        const profile = await getOrInitProfile();
        if (profile.memoryPaused) return { logged: false, reason: "paused" };
        let origin = obs.origin || originOf(obs.url || "");
        let category = obs.category || null;
        if (origin) {
          const idx = await DS().get("mine.siteIndex");
          const entry = idx[origin];
          if (entry?.paused) return { logged: false, reason: "origin-paused" };
          category = category || entry?.category || TAX().categoryForHost(origin);
          if (category && TAX().noMemoryCategories().includes(category) && !entry?.memoryOptIn) {
            return { logged: false, reason: "no-memory-zone" };
          }
        }
        const WEIGHTS = { "setting-change": 3, "profile-applied": 3, "saved-action": 3, onboarding: 3, "agent-task": 2 };
        await DS().patch("mine.episodicLog", (log) => {
          const id = (log.entries.length ? log.entries[log.entries.length - 1].id : log.cursor) + 1;
          log.entries.push({
            id,
            t: clock.now(),
            type: obs.type || "observation",
            weight: obs.weight || WEIGHTS[obs.type] || 1,
            origin: origin || null,
            category: category || null,
            data: obs.data || {},
            text: String(obs.text || "").slice(0, 400)
          });
          if (log.entries.length > 500) log.entries.splice(0, log.entries.length - 500);
          return log;
        });
        scheduleExtraction();
        if (demo2.active() && obs.type === "agent-task") {
          if (!origin) origin = "youtube.com";
          if (!category) category = "video";
        }
        const taskSucceeded = obs.data?.success || demo2.active() && obs.type === "agent-task";
        if (obs.type === "agent-task" && taskSucceeded && origin && category) {
          demo2.trace("skill", "reusable_q", "common reusable task?");
          try {
            await this._maybeProposeReusableAction(obs, origin, category);
          } catch (e) {
            console.warn("[Librarian] reusable-action proposal failed:", e.message);
          }
        }
        return { logged: true };
      },
      async _maybeProposeReusableAction(obs, origin, category) {
        const task = obs.data && obs.data.task || "";
        if (!task) return;
        const profiles = await DS().get("mine.profiles") || [];
        const exists = profiles.some((p) => p.siteTypes?.includes(category) && (p.actions || []).some((a) => (a.prompt || "").trim().toLowerCase() === task.trim().toLowerCase()));
        if (exists && !demo2.active()) return;
        const profile = await getOrInitProfile();
        const suppressions = await DS().get("mine.suppressions");
        const shortTask = task.length > 60 ? task.slice(0, 57) + "\u2026" : task;
        await this._draftProposals([{
          // Category-level aspect: "don't suggest this" silences automation
          // suggestions for this site category, not just this one task.
          aspect: `reusable-action.category:${category}`,
          aspectLabel: `running "${shortTask}" automatically on ${category} sites`,
          change: {
            op: "add-profile-action",
            siteTypes: [category],
            action: { name: shortTask, prompt: task }
          },
          rationale: `You just had the agent do this on ${origin}. I can do it automatically whenever you visit a ${category} site.`,
          evidence: []
        }], { suppressions, profile, now: clock.now() });
        demo2.trace("skill", "reusable_q", "proposed: save as skill");
        await updateBadge();
      },
      async setMemoryPaused(paused) {
        await DS().patch("mine.profile", (p) => {
          p = p || structuredClone(PROFILE_DEFAULTS);
          p.memoryPaused = !!paused;
          p.updatedAt = clock.now();
          return p;
        });
      },
      async setOriginPaused(origin, paused) {
        origin = (origin || "").toLowerCase().replace(/^www\./, "");
        await DS().patch("mine.siteIndex", (cur) => {
          cur[origin] = { ...cur[origin] || {}, paused: !!paused };
          return cur;
        });
      },
      // accept | declineOnce | suppress. Graduated consent: "not now" is a
      // 30-day cooldown; two soft declines escalate the NEXT proposal on this
      // aspect to offer permanent suppression; "suppress" writes a durable,
      // user-visible suppression record (a preference in its own right).
      async respondToProposal(id, response) {
        const props = await DS().get("mine.proposals");
        const prop = props.find((p) => p.id === id);
        if (!prop || prop.status !== "pending") return { ok: false, reason: "not-pending" };
        const now = clock.now();
        if (response === "accept") {
          if (prop.change?.op === "profile-set" && !/^fields\.[A-Za-z]/.test(String(prop.change.path || ""))) {
            return { ok: false, reason: "profile-path-not-allowed" };
          }
          prop.status = "accepted";
          if (prop.change?.op === "profile-set") {
            await this.setProfileField(prop.change.path, prop.change.value);
          } else if (prop.change?.op === "add-profile-action" && prop.change.action) {
            const siteTypes = prop.change.siteTypes || [];
            await DS().patch("mine.profiles", (profiles) => {
              profiles = profiles || [];
              let target = profiles.find((p) => p.autoApply && p.siteTypes?.some((t) => siteTypes.includes(t)));
              if (!target) {
                target = {
                  id: "profile-" + now,
                  name: `${siteTypes[0] ? siteTypes[0][0].toUpperCase() + siteTypes[0].slice(1) : "Auto"} automations`,
                  siteTypes,
                  autoApply: true,
                  settings: {},
                  actions: []
                };
                profiles.push(target);
              }
              if (!target.actions) target.actions = [];
              target.actions.push({
                id: "action-" + now,
                name: prop.change.action.name,
                prompt: prop.change.action.prompt,
                savedAt: now
              });
              return profiles;
            });
            const slug = String(prop.change.action.name || "saved-task").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "saved-task";
            const cats = siteTypes.length ? siteTypes : ["all"];
            await this.saveSkill({
              name: slug,
              description: `Runs "${prop.change.action.prompt}" for you. Use it on ${cats.join(", ")} sites.`,
              supportAreas: [],
              siteRelevance: cats,
              recipe: { adapters: [], actions: [{ name: prop.change.action.name, prompt: prop.change.action.prompt }] },
              body: `# ${prop.change.action.name}

Saved from a task the assistant completed for you. Applying this skill runs the same task on the current page.`
            });
            demo2.trace("skill", "skillsdb", "saved as skill.md");
            demo2.trace("skill", "autoenable", "skill stored");
            demo2.trace("skill", "profiledb_skill", "trigger registered");
            demo2.trace("personal", "continual", "continual update");
          } else if (prop.change?.op === "add-memory" && prop.change.record) {
            const rec = normalizeRecord({ ...prop.change.record, source: "accepted-proposal", confidence: 0.95 }, now);
            await DS().patch("mine.profile", (p) => p);
            const shard = await DS().getMemoryShard(rec.scope);
            shard.push(rec);
            await DS().setMemoryShard(rec.scope, shard);
          }
          for (const evId of prop.evidence || []) {
            const all = await kv2.getAll();
            for (const [key, recs] of Object.entries(all)) {
              if (!key.startsWith(MEMORY_PREFIX)) continue;
              const r = (recs || []).find((x) => x.id === evId);
              if (r) {
                r.confidence = Math.min(1, (r.confidence ?? 0.7) + 0.1);
                await kv2.set({ [key]: recs });
              }
            }
          }
        } else if (response === "declineOnce") {
          prop.status = "declined";
          await DS().patch("mine.suppressions", (s) => {
            const existing = s.find((x) => x.aspect === prop.aspect && x.mode === "cooldown");
            if (existing) {
              existing.until = now + 30 * 24 * 3600 * 1e3;
              existing.declineCount = (existing.declineCount || 1) + 1;
            } else {
              s.push({ id: newId("sup"), aspect: prop.aspect, mode: "cooldown", until: now + 30 * 24 * 3600 * 1e3, declineCount: 1, createdAt: now });
            }
            return s;
          });
        } else if (response === "suppress") {
          prop.status = "suppressed";
          await DS().patch("mine.suppressions", (s) => {
            s = s.filter((x) => x.aspect !== prop.aspect);
            s.push({
              id: newId("sup"),
              aspect: prop.aspect,
              mode: "permanent",
              text: `Don't suggest changes about: ${prop.aspectLabel || prop.aspect}`,
              source: "explicit-user",
              createdAt: now
            });
            return s;
          });
        } else {
          return { ok: false, reason: "bad-response" };
        }
        prop.respondedAt = now;
        await DS().set("mine.proposals", props);
        await updateBadge();
        return { ok: true, status: prop.status };
      },
      // ====================== SLOW LANE (LLM) ======================
      // Drain the episodic log behind the cursor: one Gemini call extracts
      // candidate facts AND gates them against existing same-scope memories,
      // returning ADD/UPDATE/SUPERSEDE/NOOP operations plus profile-tier
      // proposal drafts. Idempotent: cursor advances only after ops apply.
      async extract() {
        if (!_gemini) return { ran: false, reason: "no-llm" };
        const log = await DS().get("mine.episodicLog");
        const pending = log.entries.filter((e) => e.id > log.cursor);
        if (!pending.length) return { ran: false, reason: "empty" };
        const lastId = pending[pending.length - 1].id;
        const scopes = /* @__PURE__ */ new Set(["general"]);
        for (const e of pending) {
          if (e.category) scopes.add(`category:${e.category}`);
          if (e.origin) scopes.add(`origin:${e.origin}`);
        }
        const existing = [];
        for (const s of scopes) {
          for (const r of await DS().getMemoryShard(s)) {
            if (r.status === "active") existing.push({ id: r.id, scope: s, text: r.text, settings: r.settings, occurrenceCount: r.occurrenceCount });
          }
        }
        const suppressions = await DS().get("mine.suppressions");
        const now = clock.now();
        const activeSuppressed = suppressions.filter((s) => s.mode === "permanent" || s.mode === "cooldown" && s.until > now).map((s) => s.aspect);
        const profile = await getOrInitProfile();
        const prompt = `You maintain the memory of a browser accessibility assistant. Convert raw observations into durable memory operations.

## Setting keys and their EXACT units/ranges (use these units in every "settings" object)
${DS().global.tools().settingsVocabularyLines().join("\n")}

## User profile
${JSON.stringify({ supportAreas: profile.supportAreas, freeText: profile.freeText }, null, 1)}

## New observations (weight 3 = deliberate user action, 1 = ambient; cite ids as evidence)
${JSON.stringify(pending.map((e) => ({ id: e.id, type: e.type, weight: e.weight, origin: e.origin, category: e.category, text: e.text, data: e.data })), null, 1)}

## Existing memories (compare candidates against these)
${JSON.stringify(existing, null, 1)}

## Suppressed aspects (NEVER propose about these)
${JSON.stringify(activeSuppressed)}

Rules:
- Extract only durable, useful facts: preferences, repeated patterns, how-to knowledge. Ignore one-off low-weight noise (a single weight-1 event is exploration, not preference).
- scope: "general" | "category:<${TAX().categoryIds().join("|")}>" | "origin:<hostname>" | "context:<video|form|document>". Prefer the narrowest scope the evidence supports.
- For each candidate, compare to existing memories: same fact \u2192 {"op":"NOOP","id":<existing id>} (we bump its count); refines/strengthens \u2192 {"op":"UPDATE","id":...,"text":...,"settings":...}; contradicts \u2192 {"op":"SUPERSEDE","id":...,"record":{...}}; genuinely new \u2192 {"op":"ADD","record":{...}}.
- record fields: text (one plain sentence), tier ("preference"|"site"|"task"), scope, kind ("preference"|"procedural"), importance 1-10, confidence 0-1, decayClass ("stable"|"slow"|"fast"), settings (object of extension setting keys like fontScale/darkMode/autoCaptions if directly actionable, else null), evidence (array of the observation ids above that support this fact).
- Changes to the user's ABILITY PROFILE (their disability/needs themselves, not site preferences) must NOT be memory records. Emit them under "proposals" instead: {aspect:"profile.<field>", aspectLabel:"plain words", change:{op:"profile-set",path:"fields.<field>",value:...}, rationale:"<1 plain sentence why>", evidence:[]}. Only propose when evidence is strong and repeated.
- Return ONLY JSON: {"operations":[...], "proposals":[...]}`;
        let parsed;
        try {
          parsed = parseJsonLoose(await _gemini(prompt));
        } catch (e) {
          console.warn("[Librarian] extract LLM call failed:", e.message);
          return { ran: false, reason: e.message };
        }
        if (!parsed) return { ran: false, reason: "unparseable" };
        const applied = { ADD: 0, UPDATE: 0, SUPERSEDE: 0, NOOP: 0 };
        for (const op of parsed.operations || []) {
          try {
            if (op.op === "ADD" && op.record) {
              const rec = normalizeRecord(op.record, now);
              const shard = await DS().getMemoryShard(rec.scope);
              shard.push(rec);
              await DS().setMemoryShard(rec.scope, shard);
              applied.ADD++;
            } else if ((op.op === "UPDATE" || op.op === "NOOP" || op.op === "SUPERSEDE") && op.id) {
              const target = existing.find((x) => x.id === op.id);
              if (!target) continue;
              const shard = await DS().getMemoryShard(target.scope);
              const r = shard.find((x) => x.id === op.id);
              if (!r) continue;
              if (op.op === "NOOP") {
                r.occurrenceCount = (r.occurrenceCount || 1) + 1;
                r.updatedAt = now;
              } else if (op.op === "UPDATE") {
                if (op.text) r.text = String(op.text).slice(0, 500);
                if (op.settings && typeof op.settings === "object") r.settings = op.settings;
                r.occurrenceCount = (r.occurrenceCount || 1) + 1;
                r.confidence = Math.min(1, (r.confidence ?? 0.7) + 0.05);
                r.updatedAt = now;
              } else if (op.op === "SUPERSEDE" && op.record) {
                const rec = normalizeRecord(op.record, now);
                r.status = "superseded";
                r.supersededBy = rec.id;
                r.updatedAt = now;
                const destShard = rec.scope === target.scope ? shard : await DS().getMemoryShard(rec.scope);
                destShard.push(rec);
                if (rec.scope !== target.scope) await DS().setMemoryShard(rec.scope, destShard);
              }
              await DS().setMemoryShard(target.scope, shard);
              applied[op.op]++;
            }
          } catch (e) {
            console.warn("[Librarian] op apply failed:", e.message);
          }
        }
        await this._draftProposals(parsed.proposals || [], { suppressions, profile, now });
        await DS().patch("mine.episodicLog", (l) => {
          l.cursor = Math.max(l.cursor, lastId);
          return l;
        });
        await updateBadge();
        return { ran: true, applied, observations: pending.length };
      },
      // Gate + persist proposal drafts: suppression/cooldown filter, weekly
      // cap from metaPreferences, dedup against pending, plain-language pass
      // when the profile asks for it.
      async _draftProposals(drafts, { suppressions, profile, now }) {
        if (!drafts.length) return;
        const demoOn = demo2.active();
        const props = await DS().get("mine.proposals");
        const weekAgo = now - 7 * 24 * 3600 * 1e3;
        let weekCount = props.filter((p) => p.createdAt > weekAgo).length;
        const cap = demoOn ? Infinity : profile.metaPreferences?.maxProposalsPerWeek ?? 3;
        for (const d of drafts) {
          if (!d.aspect || !d.change) continue;
          if (weekCount >= cap) break;
          const sup = demoOn ? null : suppressions.find((s) => s.aspect === d.aspect && (s.mode === "permanent" || s.until > now));
          if (sup) continue;
          if (props.some((p) => p.status === "pending" && p.aspect === d.aspect)) continue;
          props.push({
            id: newId("prop"),
            aspect: d.aspect,
            aspectLabel: d.aspectLabel || d.aspect,
            change: d.change,
            rationale: String(d.rationale || "").slice(0, 300),
            evidence: d.evidence || [],
            status: "pending",
            createdAt: now,
            respondedAt: null
          });
          weekCount++;
        }
        await DS().set("mine.proposals", props);
      },
      // Daily consolidation. Deterministic where possible; LLM only for the
      // category playbooks. Idempotent — safe to re-run.
      async reflect() {
        const now = clock.now();
        const all = await kv2.getAll();
        const shards = {};
        for (const [key, recs] of Object.entries(all)) {
          if (key.startsWith(MEMORY_PREFIX)) shards[key.slice(MEMORY_PREFIX.length)] = recs || [];
        }
        const idx = await DS().get("mine.siteIndex");
        const bySettingAndCat = {};
        for (const [scope, recs] of Object.entries(shards)) {
          if (!scope.startsWith("origin:")) continue;
          const origin = scope.slice("origin:".length);
          const cat = idx[origin]?.category || TAX().categoryForHost(origin);
          if (!cat) continue;
          for (const r of recs) {
            if (r.status !== "active" || !r.settings) continue;
            for (const [k, v] of Object.entries(r.settings)) {
              const key = `${cat}|${k}|${JSON.stringify(v)}`;
              (bySettingAndCat[key] = bySettingAndCat[key] || []).push({ scope, record: r, cat, k, v });
            }
          }
        }
        let promoted = 0;
        for (const group of Object.values(bySettingAndCat)) {
          const distinctOrigins = new Set(group.map((g) => g.scope));
          if (distinctOrigins.size < 3) continue;
          const { cat, k, v } = group[0];
          const catScope = `category:${cat}`;
          const catShard = await DS().getMemoryShard(catScope);
          if (catShard.some((r) => r.status === "active" && r.settings && JSON.stringify(r.settings[k]) === JSON.stringify(v))) continue;
          const rec = normalizeRecord({
            text: `Prefers ${k} = ${JSON.stringify(v)} on ${cat} sites (seen on ${distinctOrigins.size} sites)`,
            tier: "preference",
            scope: catScope,
            kind: "preference",
            importance: 6,
            confidence: 0.85,
            decayClass: "slow",
            settings: { [k]: v },
            source: "reflection-promotion",
            occurrenceCount: group.length
          }, now);
          catShard.push(rec);
          await DS().setMemoryShard(catScope, catShard);
          for (const g of group) {
            const shard = await DS().getMemoryShard(g.scope);
            const r = shard.find((x) => x.id === g.record.id);
            if (r) {
              r.status = "superseded";
              r.supersededBy = rec.id;
              r.updatedAt = now;
            }
            await DS().setMemoryShard(g.scope, shard);
          }
          promoted++;
        }
        let expired = 0, purged = 0;
        for (const [scope, recs] of Object.entries(shards)) {
          let dirty = false;
          const kept = [];
          for (const r of await DS().getMemoryShard(scope)) {
            if (r.status === "active" && r.tier === "task" && now - (r.updatedAt || r.createdAt) > DECAY_HALF_LIFE.fast * 2) {
              r.status = "expired";
              r.updatedAt = now;
              dirty = true;
              expired++;
            }
            if ((r.status === "superseded" || r.status === "expired") && now - r.updatedAt > 30 * 24 * 3600 * 1e3) {
              purged++;
              dirty = true;
              continue;
            }
            kept.push(r);
          }
          if (dirty) await DS().setMemoryShard(scope, kept);
        }
        await DS().patch("mine.proposals", (props) => {
          for (const p of props) {
            if (p.status === "pending" && now - p.createdAt > 14 * 24 * 3600 * 1e3) p.status = "expired";
          }
          return props;
        });
        let discarded = 0;
        await DS().patch("mine.episodicLog", (log) => {
          const cutoff = now - 7 * 24 * 3600 * 1e3;
          const before = log.entries.length;
          log.entries = log.entries.filter((e) => e.id > log.cursor || e.t > cutoff);
          discarded = before - log.entries.length;
          return log;
        });
        const profile = await getOrInitProfile();
        const generalShard = await DS().getMemoryShard("general");
        const topGeneral = generalShard.filter((r) => r.status === "active").sort((a, b) => scoreRecord(b, now) - scoreRecord(a, now)).slice(0, 6);
        const coreLines = [
          `Support areas: ${profile.supportAreas.join(", ") || "not specified"}.`,
          profile.freeText ? `In their words: ${profile.freeText}` : null,
          ...topGeneral.map((r) => `- ${r.text}`)
        ].filter(Boolean);
        const views = await DS().get("mine.views");
        views.coreBlock = coreLines.join("\n");
        views.playbooks = views.playbooks || {};
        if (_gemini) {
          for (const cat of TAX().categoryIds()) {
            const recs = (await DS().getMemoryShard(`category:${cat}`)).filter((r) => r.status === "active");
            if (recs.length < 3) continue;
            try {
              const md = await _gemini(
                `Write a short markdown playbook (max 120 words, plain language) for helping this user on ${cat} websites, based on these memories:
` + recs.map((r) => `- ${r.text}`).join("\n") + `
User support areas: ${profile.supportAreas.join(", ")}. Output only the playbook markdown.`
              );
              if (md) views.playbooks[cat] = md.trim().slice(0, 1500);
            } catch {
            }
          }
        }
        views.renderedAt = now;
        await DS().set("mine.views", views);
        for (const scope of Object.keys(shards)) {
          const recs = await DS().getMemoryShard(scope);
          const ids = new Set(recs.map((r) => r.id));
          let dirty = false;
          for (const r of recs) {
            if (r.supersededBy && !ids.has(r.supersededBy)) {
              r.supersededBy = null;
              dirty = true;
            }
          }
          if (dirty) await DS().setMemoryShard(scope, recs);
        }
        await updateBadge();
        return { ran: true, promoted, expired, purged, discarded };
      }
    };
    let _extractTimer = null;
    function scheduleExtraction() {
      if (_extractTimer) clearTimeout(_extractTimer);
      _extractTimer = setTimeout(() => {
        _extractTimer = null;
        Librarian.extract().catch((e) => console.warn("[Librarian] extract failed:", e.message));
      }, 2e4);
    }
    async function updateBadge() {
      try {
        const pending = await Librarian.listProposals("pending");
        await notifier2.pending(pending.length);
      } catch {
      }
    }
    return Librarian;
  }

  // ../toolkit/core/broker.js
  var READ_SCOPES = [
    "ability.supportAreas",
    "ability.text",
    "ability.vision",
    "ability.motion",
    "ability.audio",
    "ability.input",
    "ability.cognition",
    "ability.freeText"
  ];
  var DIMENSION_BY_SCOPE = {
    "ability.supportAreas": "supportAreas",
    "ability.text": "text",
    "ability.vision": "vision",
    "ability.motion": "motion",
    "ability.audio": "audio",
    "ability.input": "input",
    "ability.cognition": "cognition",
    "ability.freeText": "freeText"
  };
  var AUDIENCES = ["personal", "friends", "anyone"];
  var AUDIENCE_ORDER = { personal: 0, friends: 1, anyone: 2 };
  var ALLOWED_INSIGHT_OPS = /* @__PURE__ */ new Set(["add-memory", "add-profile-action"]);
  var UNSAFE_KEYS = /* @__PURE__ */ new Set(["__proto__", "prototype", "constructor"]);
  function hasUnsafeKeys(value, depth = 0) {
    if (depth > 6 || value === null || typeof value !== "object") return false;
    for (const [k, v] of Object.entries(value)) {
      if (UNSAFE_KEYS.has(k)) return true;
      if (hasUnsafeKeys(v, depth + 1)) return true;
    }
    return false;
  }
  function createBroker({ datastore, librarian: librarian2, clock = { now: () => Date.now() } }) {
    const DS = datastore;
    function newId(prefix) {
      return `${prefix}-${clock.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
    }
    async function audit(entry) {
      await DS().patch("mine.shareAudit", (log) => {
        log.push({ ...entry, t: clock.now() });
        if (log.length > 500) log.splice(0, log.length - 500);
        return log;
      });
    }
    async function requireGrant(grantId) {
      const grants = await DS().get("mine.grants");
      const g = grants.find((x) => x.id === grantId);
      if (!g) throw new Error(`Broker: unknown grant "${grantId}"`);
      if (g.revokedAt) throw new Error(`Broker: grant "${grantId}" was revoked`);
      return g;
    }
    return {
      READ_SCOPES,
      async listGrants() {
        return await DS().get("mine.grants");
      },
      /**
       * Create a grant for an app. The USER creates grants (through consent
       * UI); apps request them. Default deny: empty read/write until granted.
       * @param {{ appId: string, appName?: string, read?: string[], write?: boolean,
       *           audience?: 'personal'|'friends'|'anyone' }} req
       */
      async createGrant({ appId, appName = "", read = [], write = false, audience = "personal" }) {
        if (!appId) throw new Error("Broker: appId required");
        const bad = read.filter((s) => !READ_SCOPES.includes(s));
        if (bad.length) throw new Error(`Broker: unknown read scopes: ${bad.join(", ")}`);
        if (!AUDIENCES.includes(audience)) throw new Error(`Broker: unknown audience "${audience}"`);
        const grant = {
          id: newId("grant"),
          appId,
          appName,
          read: [...new Set(read)],
          write: !!write,
          // may contribute insights (as proposals)
          audience,
          // who this grant's holder is to the person
          createdAt: clock.now(),
          revokedAt: null
        };
        await DS().patch("mine.grants", (grants) => {
          grants.push(grant);
          return grants;
        });
        await audit({ kind: "grant-created", grantId: grant.id, appId, read: grant.read, write: grant.write });
        return grant;
      },
      async revokeGrant(grantId) {
        let found = false;
        await DS().patch("mine.grants", (grants) => {
          const g = grants.find((x) => x.id === grantId);
          if (g && !g.revokedAt) {
            g.revokedAt = clock.now();
            found = true;
          }
          return grants;
        });
        if (found) await audit({ kind: "grant-revoked", grantId });
        return found;
      },
      /**
       * Export the person's understanding for an app: the AbilityModel
       * filtered to the grant's read scopes. Ungrated dimensions come back as
       * `undefined` — absent, not zeroed, so the consumer can't confuse "no
       * access" with "typical ability". Raw memories/episodic log are not
       * reachable through this API at all.
       */
      async exportUnderstanding(grantId) {
        const g = await requireGrant(grantId);
        const profile = await librarian2.getProfile();
        const sharing = profile?.metaPreferences?.sharing || "personal";
        const audience = g.audience || "personal";
        if ((AUDIENCE_ORDER[audience] ?? Infinity) > AUDIENCE_ORDER[sharing]) {
          await audit({ kind: "export-blocked", grantId: g.id, appId: g.appId, audience, sharing });
          throw new Error(`Broker: profile sharing is "${sharing}" \u2014 a "${audience}" grant may not read it`);
        }
        const model = await librarian2.getAbilityModel();
        const out = {
          schemaVersion: model.schemaVersion,
          provenance: { source: "librarian", grantId: g.id, appId: g.appId, sharedAt: clock.now() },
          confidence: {}
        };
        for (const scope of g.read) {
          const dim = DIMENSION_BY_SCOPE[scope];
          out[dim] = structuredClone(model[dim]);
          for (const [path, conf] of Object.entries(model.confidence)) {
            if (path === dim || path.startsWith(dim + ".")) out.confidence[path] = conf;
          }
        }
        await audit({ kind: "export", grantId: g.id, appId: g.appId, scopes: g.read });
        return out;
      },
      /**
       * An app contributes an insight back (e.g. XR: "FOV measurement suggests
       * larger text"). Requires write permission. NEVER auto-applies: it lands
       * in the Librarian's proposal queue with full provenance, subject to the
       * same suppression/cooldown/weekly-cap gates as internal inferences.
       * @param {string} grantId
       * @param {{ aspect: string, aspectLabel?: string, change: object,
       *           rationale?: string, confidence?: number }} insight
       */
      async importInsight(grantId, insight) {
        const g = await requireGrant(grantId);
        if (!g.write) throw new Error(`Broker: grant "${grantId}" has no write permission`);
        if (!insight?.aspect || !insight?.change) throw new Error("Broker: insight needs aspect + change");
        if (!ALLOWED_INSIGHT_OPS.has(insight.change.op)) {
          throw new Error(`Broker: insight op "${insight.change.op}" not permitted for external apps`);
        }
        if (hasUnsafeKeys(insight.change)) {
          throw new Error("Broker: insight change contains unsafe keys");
        }
        const accepted = await librarian2.proposeInsight({
          aspect: insight.aspect,
          aspectLabel: insight.aspectLabel || insight.aspect,
          change: insight.change,
          rationale: insight.rationale || "",
          evidence: []
        }, { source: g.appId, grantId: g.id, confidence: insight.confidence });
        await audit({ kind: "import", grantId: g.id, appId: g.appId, aspect: insight.aspect, accepted });
        return { queued: accepted };
      },
      async getAuditLog() {
        return await DS().get("mine.shareAudit");
      }
    };
  }

  // ../toolkit/adapters/chrome/librarian.entry.js
  var kv = {
    getAll: () => chrome.storage.local.get(null),
    set: (items) => chrome.storage.local.set(items)
  };
  var notifier = {
    async pending(count) {
      await chrome.action.setBadgeText({ text: count ? String(count) : "" });
      if (count) await chrome.action.setBadgeBackgroundColor({ color: "#1a73e8" });
    }
  };
  var demo = {
    active: () => !!globalThis.AA_DEMO_MODE,
    trace: (diagram, region, label) => {
      if (globalThis.aaDemoTrace) globalThis.aaDemoTrace(diagram, region, label);
    }
  };
  var librarian = createLibrarian({
    datastore: () => globalThis.Datastore,
    taxonomy: () => globalThis.AA_TAXONOMY,
    kv,
    notifier,
    demo,
    clock: { now: () => Date.now() }
  });
  globalThis.Librarian = librarian;
  globalThis.Broker = createBroker({
    datastore: () => globalThis.Datastore,
    librarian,
    clock: { now: () => Date.now() }
  });
  if (chrome.alarms && !globalThis._aaLibrarianAlarmsInstalled) {
    chrome.alarms.create("aaLibrarianExtract", { periodInMinutes: 30 });
    chrome.alarms.create("aaLibrarianReflect", { periodInMinutes: 60 * 24 });
    chrome.alarms.onAlarm.addListener((alarm) => {
      if (alarm.name === "aaLibrarianExtract") {
        librarian.extract().catch((e) => console.warn("[Librarian] extract failed:", e.message));
      } else if (alarm.name === "aaLibrarianReflect") {
        librarian.reflect().catch((e) => console.warn("[Librarian] reflect failed:", e.message));
      }
    });
    globalThis._aaLibrarianAlarmsInstalled = true;
  }
})();
