// GENERATED by build.js from /toolkit (ES module source). Do not edit by hand.
(() => {
  // ../toolkit/ports/index.js
  var noopDemo = {
    isOn: () => false,
    trace: () => {
    }
  };
  var noopConsent = {
    notifyPending: () => {
    }
  };
  var noopScheduler = {
    every: () => {
    },
    debounce: () => {
    }
  };

  // ../toolkit/core/units.js
  var UNIT = Object.freeze({
    percent: "percent",
    // 100 = no change (fontScale)
    ratio: "ratio",
    // a unitless multiple (lineHeight, speechRate)
    em: "em",
    // typographic em (letterSpacing)
    boolean: "boolean",
    enum: "enum"
  });
  var SETTING_UNITS = Object.freeze({
    fontScale: UNIT.percent,
    lineHeight: UNIT.ratio,
    letterSpacing: UNIT.em,
    speechRate: UNIT.ratio
  });
  function coerceSetting(key, value, meta) {
    const m = meta && meta[key];
    if (!(m && m.type === "number" && Array.isArray(m.range) && typeof value === "number")) {
      return value;
    }
    const [min, max] = m.range;
    let val = value;
    if (val < min && val * 100 >= min && val * 100 <= max) val = val * 100;
    return Math.min(max, Math.max(min, val));
  }
  function coerceSettings(settings, meta) {
    if (!settings || typeof settings !== "object") return settings;
    const out = {};
    for (const [k, v] of Object.entries(settings)) out[k] = coerceSetting(k, v, meta);
    return out;
  }
  function clampSetting(key, value, meta) {
    const m = meta && meta[key];
    if (!(m && m.type === "number" && Array.isArray(m.range) && typeof value === "number")) {
      return value;
    }
    const [min, max] = m.range;
    return Math.min(max, Math.max(min, value));
  }
  function clampSettings(settings, meta) {
    if (!settings || typeof settings !== "object") return settings;
    const out = {};
    for (const [k, v] of Object.entries(settings)) out[k] = clampSetting(k, v, meta);
    return out;
  }

  // ../toolkit/core/strength.js
  var STRENGTH_RANK = Object.freeze({ hint: 0, preference: 1, floor: 2 });
  function rankOf(strength) {
    const r = STRENGTH_RANK[strength];
    return r === void 0 ? STRENGTH_RANK.preference : r;
  }

  // ../toolkit/core/ability.js
  var VALID_STRENGTH = ["floor", "preference", "hint"];
  var VALID_UNIT = ["ratio", "em", "percent", "boolean", "enum"];
  function normalizeNeed(n) {
    if (!n || typeof n !== "object" || !n.dimension) return null;
    const need = {
      dimension: String(n.dimension),
      value: n.value,
      strength: VALID_STRENGTH.includes(n.strength) ? n.strength : "preference"
    };
    if (VALID_UNIT.includes(n.unit)) need.unit = n.unit;
    if (n.confidence != null) need.confidence = n.confidence;
    if (n.source) need.source = String(n.source);
    return need;
  }
  function toAbilityModel(profile) {
    const fields = profile && profile.fields || {};
    const needs = Array.isArray(fields.needs) ? fields.needs.map(normalizeNeed).filter(Boolean) : [];
    return {
      schemaVersion: 1,
      supportAreas: profile && profile.supportAreas || [],
      freeText: profile && profile.freeText || "",
      language: profile && profile.metaPreferences && profile.metaPreferences.language || "standard",
      readingLevel: fields.readingLevel != null ? fields.readingLevel : null,
      confidence: fields.confidence != null ? fields.confidence : null,
      needs
    };
  }

  // ../toolkit/core/memory-class.js
  function memoryClassOf(record) {
    const kind = record && record.kind;
    if (kind === "observation") return "episodic";
    if (kind === "procedural") return "procedural";
    return "semantic";
  }

  // ../toolkit/sync/grants.js
  var GRANT_SCOPES = [
    "ability.categories",
    // coarse support-area labels (vision/hearing/motor/cognitive)
    "reading.level",
    // the reading-level hint
    "language",
    // 'standard' | 'plain'
    "settings.text"
    // structured, modality-NEUTRAL display needs (needs[]) — never web fontScale
  ];
  var SCOPE_PROJECTION = {
    "ability.categories": (am) => ({ supportAreas: Array.isArray(am.supportAreas) ? am.supportAreas.map(String) : [] }),
    "reading.level": (am) => ({ readingLevel: am.readingLevel ?? null }),
    "language": (am) => ({ language: am.language || "standard" }),
    "settings.text": (am) => ({ needs: Array.isArray(am.needs) ? am.needs.map((n) => ({ ...n })) : [] })
  };
  function validateScopes(scopes) {
    if (!Array.isArray(scopes) || scopes.length === 0) return false;
    return scopes.every((s) => GRANT_SCOPES.includes(s));
  }
  function normalizeGrant(raw) {
    const g = raw || {};
    return {
      id: g.id || null,
      appId: String(g.appId || ""),
      appLabel: String(g.appLabel || g.appId || ""),
      scopes: Array.isArray(g.scopes) ? g.scopes.filter((s) => GRANT_SCOPES.includes(s)) : [],
      grantedAt: Number(g.grantedAt) || 0
    };
  }
  function isActive(grant) {
    return !!(grant && grant.appId && Array.isArray(grant.scopes) && grant.scopes.length > 0);
  }
  function filterAbilityModelByScopes(abilityModel, scopes) {
    const am = abilityModel || {};
    const out = { schemaVersion: am.schemaVersion ?? 1 };
    for (const s of scopes || []) {
      const project = SCOPE_PROJECTION[s];
      if (project) Object.assign(out, project(am));
    }
    return out;
  }

  // ../toolkit/core/librarian.js
  function createLibrarian({
    datastore,
    taxonomy,
    clock,
    scheduler = noopScheduler,
    consent = noopConsent,
    demo = noopDemo
  }) {
    if (!datastore) throw new Error("createLibrarian: datastore is required");
    if (!taxonomy) throw new Error("createLibrarian: taxonomy is required");
    if (!clock) throw new Error("createLibrarian: clock port is required");
    const DS = () => datastore;
    const TAX = () => taxonomy;
    let _gemini = null;
    function newId(prefix) {
      return `${prefix}-${clock.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
    }
    function originOf(url) {
      try {
        return new URL(url).hostname.toLowerCase().replace(/^www\./, "");
      } catch {
        return null;
      }
    }
    function parseJsonLoose(text) {
      if (!text) return null;
      let t = String(text).trim().replace(/^```(?:json)?\s*/i, "").replace(/```\s*$/, "");
      try {
        return JSON.parse(t);
      } catch {
      }
      const m = t.match(/\{[\s\S]*\}/);
      if (m) {
        try {
          return JSON.parse(m[0]);
        } catch {
        }
      }
      return null;
    }
    const DECAY_HALF_LIFE = {
      stable: Infinity,
      slow: 1e3 * 60 * 60 * 24 * 90,
      // ~90 days
      fast: 1e3 * 60 * 60 * 24 * 7
      // ~7 days
    };
    function scoreRecord(r, now) {
      const half = DECAY_HALF_LIFE[r.decayClass] || DECAY_HALF_LIFE.slow;
      const age = now - (r.lastConfirmedAt || r.updatedAt || r.createdAt || now);
      const recency = half === Infinity ? 1 : Math.pow(0.5, age / half);
      return recency * ((r.importance || 5) / 10) * (r.confidence ?? 0.7);
    }
    function conditionsMet(r, now) {
      if (!r.conditions) return true;
      const d = new Date(now);
      if (r.conditions.timeOfDay) {
        const h = d.getHours();
        const { fromHour = 0, toHour = 24 } = r.conditions.timeOfDay;
        const inWindow = fromHour <= toHour ? h >= fromHour && h < toHour : h >= fromHour || h < toHour;
        if (!inWindow) return false;
      }
      if (Array.isArray(r.conditions.daysOfWeek) && r.conditions.daysOfWeek.length) {
        if (!r.conditions.daysOfWeek.includes(d.getDay())) return false;
      }
      return true;
    }
    const VALID_SCOPE = /^(general|category:[a-z-]+|context:[a-z-]+|origin:[a-z0-9.-]+|tool:[a-zA-Z0-9_-]+)$/;
    function settingsMeta() {
      try {
        return DS().global.tools().settingsMeta || {};
      } catch (_) {
        return {};
      }
    }
    function sanitizeSettings(settings) {
      if (!settings || typeof settings !== "object") return settings;
      return coerceSettings(settings, settingsMeta());
    }
    function clampForRead(settings) {
      if (!settings || typeof settings !== "object") return settings;
      return clampSettings(settings, settingsMeta());
    }
    function normalizeRecord(raw, now) {
      const r = { ...raw };
      r.id = r.id || newId("mem");
      r.text = String(r.text || "").slice(0, 500);
      r.tier = ["profile", "preference", "site", "task"].includes(r.tier) ? r.tier : "preference";
      r.scope = VALID_SCOPE.test(r.scope || "") ? r.scope : "general";
      r.kind = ["preference", "procedural", "suppression", "rule", "observation"].includes(r.kind) ? r.kind : "preference";
      r.strength = ["floor", "preference", "hint"].includes(r.strength) ? r.strength : "preference";
      r.importance = Math.min(10, Math.max(1, Number(r.importance) || 5));
      r.confidence = Math.min(1, Math.max(0, Number(r.confidence ?? 0.7)));
      r.decayClass = ["stable", "slow", "fast"].includes(r.decayClass) ? r.decayClass : "slow";
      r.conditions = r.conditions || null;
      r.settings = r.settings && typeof r.settings === "object" ? sanitizeSettings(r.settings) : null;
      r.aspect = r.aspect || null;
      r.occurrenceCount = Math.max(1, Number(r.occurrenceCount) || 1);
      r.firstSeenAt = r.firstSeenAt || now;
      r.createdAt = r.createdAt || now;
      r.updatedAt = now;
      r.lastAccessed = r.lastAccessed || now;
      r.lastConfirmedAt = r.lastConfirmedAt || r.createdAt || now;
      r.status = ["active", "superseded", "expired"].includes(r.status) ? r.status : "active";
      r.supersededBy = r.supersededBy || null;
      r.source = r.source || "inferred";
      r.evidence = Array.isArray(r.evidence) ? r.evidence.slice(-20) : [];
      return r;
    }
    function scopesFor(url, contexts) {
      const scopes = ["general"];
      for (const c of contexts || []) {
        if (TAX().contexts.some((x) => x.id === c)) scopes.push(`context:${c}`);
      }
      const origin = originOf(url);
      return { scopes, origin };
    }
    async function loadScopeShards(url, contexts) {
      const { scopes, origin } = scopesFor(url, contexts);
      let category = null;
      if (origin) {
        category = await Librarian.getSiteCategory(origin);
        if (category) scopes.splice(scopes.length, 0, `category:${category}`);
        scopes.push(`origin:${origin}`);
      }
      const shards = {};
      for (const s of scopes) shards[s] = await DS().getMemoryShard(s);
      return { scopes, shards, origin, category };
    }
    const PROFILE_DEFAULTS = {
      schemaVersion: 1,
      supportAreas: [],
      freeText: "",
      fields: {},
      // canonical ability fields, e.g. { vision: { fontScale: 130 } }
      metaPreferences: {
        consentBoundary: "profile-only",
        // 'profile-only' | 'all-tiers'
        language: "standard",
        // 'standard' | 'plain'
        maxProposalsPerWeek: 30
      },
      memoryPaused: false
    };
    async function getOrInitProfile() {
      let p = await DS().get("mine.profile");
      if (!p) {
        const legacy = await DS().get("mine.onboardingProfile");
        p = structuredClone(PROFILE_DEFAULTS);
        if (legacy) {
          p.supportAreas = legacy.supportAreas || [];
          p.freeText = legacy.freeText || "";
        }
        p.createdAt = clock.now();
        p.updatedAt = clock.now();
        await DS().set("mine.profile", p);
      }
      return p;
    }
    const Librarian = {
      setGeminiCaller(fn) {
        _gemini = fn;
      },
      // ====================== FAST LANE (no LLM) ======================
      async getProfile() {
        return await getOrInitProfile();
      },
      // The modality-agnostic AbilityModel view (../core/ability). Pure read,
      // fast lane — what a non-web surface (XR, ArtInsight) reads to derive its
      // own rendering. Today's profiles project to an empty `needs[]`.
      //
      // READ-ONLY by design: it must NOT materialize mine.profile. It runs on the
      // per-navigation effective-prefs hot path (via resolveWebPreferences); using
      // getOrInitProfile() would add a first-call write to sync storage and race
      // onboarding/popup. So we read the stored profile and, if absent, project
      // the legacy seed in-memory without persisting anything.
      async getAbilityModel() {
        let p = await DS().get("mine.profile");
        if (!p) {
          const legacy = await DS().get("mine.onboardingProfile");
          p = legacy ? { supportAreas: legacy.supportAreas || [], freeText: legacy.freeText || "", fields: {}, metaPreferences: {} } : null;
        }
        return toAbilityModel(p);
      },
      // User-initiated edit — bypasses the proposal gate by design (the gate
      // exists for *inferred* changes; explicit user intent needs no consent).
      async setProfileField(path, value) {
        return await DS().patch("mine.profile", async (p) => {
          p = p || structuredClone(PROFILE_DEFAULTS);
          const parts = String(path).split(".");
          let obj = p;
          for (let i = 0; i < parts.length - 1; i++) {
            if (typeof obj[parts[i]] !== "object" || obj[parts[i]] == null) obj[parts[i]] = {};
            obj = obj[parts[i]];
          }
          obj[parts[parts.length - 1]] = value;
          p.updatedAt = clock.now();
          return p;
        });
      },
      // Fast lane for manual setting flips (popup toggle, onboarding choice).
      // A deliberate change is the strongest preference signal there is, so it
      // is recorded immediately as a durable user-explicit record that gets
      // FINAL say in getEffectivePreferences — without this, an auto-apply
      // profile or a learned record re-imposes the old value on the next page
      // and the user's change silently "doesn't stick". One record per setting
      // key, updated in place on subsequent changes. Recorded even while
      // memory is paused: this is a direct user command, not an inference.
      async recordExplicitSetting(key, value, origin) {
        return this.recordScopedSettings("general", { [key]: value }, { origin });
      },
      // Generalized explicit-setting writer: upserts one durable user-explicit
      // record PER setting key at the given scope (general | category:<id> |
      // origin:<host> | context:<id>). These get final say in
      // getEffectivePreferences, but a scoped record only loads when the page
      // matches that scope — so "make news sites easier to read" lands on
      // category:news and does NOT leak to every site. scopeLabel is a
      // human phrase for the record text. Returns the record ids.
      async recordScopedSettings(scope, settings, opts = {}) {
        const now = clock.now();
        scope = VALID_SCOPE.test(scope || "") ? scope : "general";
        const where = opts.scopeLabel || (scope === "general" ? "" : scope.startsWith("category:") ? ` on ${scope.slice(9)} sites` : scope.startsWith("origin:") ? ` on ${scope.slice(7)}` : scope.startsWith("context:") ? ` for ${scope.slice(8)} content` : "");
        const shard = await DS().getMemoryShard(scope);
        const ids = [];
        for (const [key, value] of Object.entries(settings || {})) {
          const aspect = `setting.${key}`;
          const text = `You set ${key} to ${JSON.stringify(value)}${where}.`;
          let rec = shard.find((r) => r.source === "user-explicit" && r.aspect === aspect && r.status === "active");
          if (rec) {
            rec.settings = sanitizeSettings({ [key]: value });
            rec.text = text;
            rec.occurrenceCount = (rec.occurrenceCount || 1) + 1;
            rec.updatedAt = now;
            rec.lastAccessed = now;
            rec.lastConfirmedAt = now;
          } else {
            rec = normalizeRecord({
              kind: "preference",
              tier: "preference",
              scope,
              aspect,
              source: "user-explicit",
              confidence: 1,
              importance: 8,
              decayClass: "stable",
              settings: { [key]: value },
              text
            }, now);
            shard.push(rec);
          }
          ids.push(rec.id);
        }
        await DS().setMemoryShard(scope, shard);
        return ids;
      },
      // Classify once, cache forever; user override wins and is sticky.
      // Deterministic by default — pass {allowLlm: true, title} to let the
      // background's classify handler fall through to Gemini for unknown hosts.
      async getSiteCategory(origin, opts = {}) {
        origin = (origin || "").toLowerCase().replace(/^www\./, "");
        if (!origin) return null;
        const idx = await DS().get("mine.siteIndex");
        const hit = idx[origin];
        if (hit && (hit.source === "user" || hit.taxonomyVersion === TAX().version)) {
          return hit.category;
        }
        let category = TAX().categoryForHost(origin);
        let source = "hostmap";
        if (!category && opts.allowLlm && _gemini) {
          try {
            const valid = TAX().categoryIds();
            const out = await _gemini(
              `Classify this website into exactly one category. Hostname: "${origin}", Title: "${opts.title || ""}". Categories: ${valid.join(", ")}. Return ONLY the category word, nothing else.`
            );
            const cleaned = (out || "").trim().toLowerCase();
            category = valid.includes(cleaned) ? cleaned : "other";
            source = "llm";
          } catch {
            category = null;
          }
        }
        if (category) {
          await DS().patch("mine.siteIndex", (cur) => {
            cur[origin] = { category, source, classifiedAt: clock.now(), taxonomyVersion: TAX().version, ...cur[origin]?.paused ? { paused: true } : {} };
            return cur;
          });
        }
        return category;
      },
      async setSiteCategoryOverride(origin, category) {
        origin = (origin || "").toLowerCase().replace(/^www\./, "");
        await DS().patch("mine.siteIndex", (cur) => {
          cur[origin] = { ...cur[origin] || {}, category, source: "user", classifiedAt: clock.now(), taxonomyVersion: TAX().version };
          return cur;
        });
      },
      // Deterministic scope-chain merge of machine-actionable settings.
      // Order (later wins): general → context → category → explicit
      // customProfile (user-authored beats inferred at category level) →
      // origin. Rule records (kind 'rule') in a shard apply after that
      // shard's preferences. Conditions (time windows) filter throughout.
      async getEffectivePreferences(url, contexts = []) {
        const now = clock.now();
        const { scopes, shards, origin, category } = await loadScopeShards(url, contexts);
        const merged = {};
        const applied = [];
        const provenance = {};
        const strengthAt = {};
        const assign = (src, scope, strength = "preference") => {
          const clean = clampForRead(src) || {};
          const r = rankOf(strength);
          for (const [k, v] of Object.entries(clean)) {
            if (k in merged && r < (strengthAt[k] ?? STRENGTH_RANK.preference)) continue;
            merged[k] = v;
            provenance[k] = scope;
            strengthAt[k] = r;
          }
        };
        const explicit = [];
        const applyShard = (scope) => {
          const recs = (shards[scope] || []).filter((r) => r.status === "active" && r.settings && conditionsMet(r, now)).sort((a, b) => (a.kind === "rule") - (b.kind === "rule"));
          for (const r of recs) {
            if (r.source === "user-explicit") {
              explicit.push({ r, scope });
              continue;
            }
            assign(r.settings, scope, r.strength);
            applied.push({ id: r.id, scope, text: r.text });
          }
        };
        for (const s of scopes) {
          if (s.startsWith("origin:")) continue;
          applyShard(s);
          if (s.startsWith("category:") && category) {
            const profiles = await DS().get("mine.profiles") || [];
            const match = profiles.find((p) => p.autoApply && p.siteTypes?.includes(category));
            if (match?.settings) {
              assign(match.settings, s);
              applied.push({ id: match.id, scope: s, text: `Profile "${match.name}"`, explicit: true });
            }
          }
        }
        if (origin) applyShard(`origin:${origin}`);
        const specificity = (sc) => sc.startsWith("origin:") ? 3 : sc.startsWith("category:") ? 2 : sc.startsWith("context:") ? 1 : 0;
        explicit.sort((a, b) => specificity(a.scope) - specificity(b.scope) || (a.r.updatedAt || 0) - (b.r.updatedAt || 0));
        for (const { r, scope } of explicit) {
          assign(r.settings, scope, r.strength);
          applied.push({ id: r.id, scope, text: r.text, explicit: true });
        }
        return { settings: merged, applied, provenance, category, origin };
      },
      // Context block for agent prompts: core memory block + scored facts for
      // this page + category playbook. Deterministic; markdown at the
      // boundary, records at rest.
      async recall(url, task = "", contexts = []) {
        const now = clock.now();
        const { scopes, shards, origin, category } = await loadScopeShards(url, contexts);
        const profile = await getOrInitProfile();
        const views = await DS().get("mine.views");
        const facts = [];
        for (const s of scopes) {
          for (const r of shards[s] || []) {
            if (r.status !== "active" || r.kind === "suppression" || !conditionsMet(r, now)) continue;
            facts.push({ ...r, _scope: s, _score: scoreRecord(r, now), _memoryClass: memoryClassOf(r) });
          }
        }
        facts.sort((a, b) => b._score - a._score);
        const top = facts.slice(0, 12);
        const touched = new Set(top.map((r) => r.id));
        for (const s of new Set(top.map((r) => r._scope))) {
          const shard = shards[s].map((r) => touched.has(r.id) ? { ...r, lastAccessed: now } : r);
          await DS().setMemoryShard(s, shard);
        }
        const lines = [];
        const core = views.coreBlock || `Support areas: ${profile.supportAreas.join(", ") || "not specified"}.` + (profile.freeText ? ` Notes: ${profile.freeText}` : "");
        lines.push("### About this user", core);
        const byScope = (pred, title) => {
          const hits = top.filter(pred);
          if (hits.length) {
            lines.push(`### ${title}`);
            for (const f of hits) lines.push(`- ${f.text}`);
          }
        };
        byScope((f) => f._scope === "general", "General preferences");
        byScope((f) => f._scope.startsWith("context:"), "For this kind of content");
        byScope((f) => f._scope.startsWith("category:"), category ? `On ${category} sites` : "On sites like this");
        byScope((f) => f._scope.startsWith("origin:"), origin ? `On ${origin}` : "On this site");
        const playbook = category && views.playbooks && views.playbooks[category];
        if (playbook) lines.push(`### Playbook: ${category} sites`, playbook);
        return { block: lines.join("\n"), facts: top, profile, category, origin };
      },
      async listMemories(filter = {}) {
        const out = [];
        const shards = await DS().allMemoryShards();
        for (const [scope, recs] of Object.entries(shards)) {
          for (const r of recs || []) {
            if (filter.status && r.status !== filter.status) continue;
            if (filter.scope && scope !== filter.scope) continue;
            out.push({ ...r, scope, memoryClass: memoryClassOf(r) });
          }
        }
        const supp = await DS().get("mine.suppressions");
        return { memories: out, suppressions: supp };
      },
      async deleteMemory(id) {
        const shards = await DS().allMemoryShards();
        for (const [scope, recs] of Object.entries(shards)) {
          const idx = (recs || []).findIndex((r) => r.id === id);
          if (idx >= 0) {
            recs.splice(idx, 1);
            await DS().setMemoryShard(scope, recs);
            return true;
          }
        }
        const removed = await DS().patch("mine.suppressions", (s) => s.filter((x) => x.id !== id));
        return Array.isArray(removed);
      },
      async listProposals(status = "pending") {
        const props = await DS().get("mine.proposals");
        return status ? props.filter((p) => p.status === status) : props;
      },
      // ====================== CROSS-APP GRANTS (Phase 3) ======================
      // A first-party app reads a scoped, modality-neutral slice of the
      // AbilityModel ONLY behind a grant the user approved and can see.
      // DEFAULT-DENY: no grant, no read. A request is NOT a grant — it is drafted
      // as an ordinary proposal through the SAME consent machinery (suppression /
      // cooldown / weekly cap), and only respondToProposal('accept') on the local
      // user surface mints the grant. The requesting app has no code path that
      // resolves its own request (sender-cannot-self-resolve, structurally).
      // Ask the user (via a proposal) for read access to `scopes` of the
      // AbilityModel. Validates against the closed GRANT_SCOPES whitelist; if an
      // active grant already covers every requested scope, does nothing. Returns
      // the pending proposal's id, or {ok:false} when rejected/suppressed.
      async requestGrant(appId, scopes, opts = {}) {
        appId = String(appId || "").trim();
        if (!appId) return { ok: false, reason: "bad-app" };
        if (!validateScopes(scopes)) return { ok: false, reason: "bad-scope" };
        const grants = await DS().get("mine.grants") || [];
        const existing = grants.find((g) => g.appId === appId && isActive(g));
        if (existing && scopes.every((s) => existing.scopes.includes(s))) {
          return { ok: false, reason: "already-granted" };
        }
        const appLabel = String(opts.appLabel || appId).slice(0, 100);
        const now = clock.now();
        const suppressions = await DS().get("mine.suppressions");
        const profile = await getOrInitProfile();
        await this._draftProposals([{
          aspect: `grant:${appId}`,
          aspectLabel: `let ${appLabel} read your ${scopes.join(", ")}`,
          change: { op: "grant-request", appId, appLabel, scopes },
          rationale: String(opts.rationale || `${appLabel} wants to read part of your accessibility profile so it can adapt itself for you.`).slice(0, 300),
          evidence: []
        }], { suppressions, profile, now });
        await updateBadge();
        const props = await DS().get("mine.proposals");
        const pending = props.find((p) => p.status === "pending" && p.aspect === `grant:${appId}` && p.change && p.change.op === "grant-request");
        return pending ? { ok: true, proposalId: pending.id } : { ok: false, reason: "suppressed" };
      },
      // The "what each app can see" panel's data: live (active) grants only —
      // revoke is a delete, so anything still stored is active.
      async listGrants() {
        const grants = await DS().get("mine.grants") || [];
        return grants.filter(isActive);
      },
      // Revoke = LOCAL DELETE (no tombstone, no propagation). Idempotent.
      async revokeGrant(appId) {
        appId = String(appId || "").trim();
        await DS().patch("mine.grants", (grants) => (grants || []).filter((g) => g.appId !== appId));
        return { ok: true };
      },
      // Read-only, default-deny export of the granted AbilityModel slice. No
      // active grant for `appId` → no data. Never writes; never includes a
      // SurfaceProfile (web fontScale etc.) — only the modality-neutral,
      // categories-only AbilityModel, filtered to the grant's scopes.
      async exportAbilityModel(appId) {
        appId = String(appId || "").trim();
        const grants = await DS().get("mine.grants") || [];
        const grant = grants.find((g) => g.appId === appId && isActive(g));
        if (!grant) return { ok: false, reason: "no-grant" };
        const abilityModel = await this.getAbilityModel();
        return { ok: true, abilityModel: filterAbilityModelByScopes(abilityModel, grant.scopes) };
      },
      // ====================== ACTING USER (Phase 3) ======================
      // A lightweight "who's using this now?" partition so two people on one
      // device/headset never cross-contaminate. The datastore owns the physical
      // key-derivation (every mine.* store + memory shard is namespaced by the
      // active partition; null = the default single-user data, unchanged); the
      // Librarian just exposes the switch and refreshes the badge, since the
      // pending-proposal count is per-partition.
      async setActingUser(id, opts = {}) {
        const res = await DS().setActingUser(id, opts);
        await updateBadge();
        return res;
      },
      getActingUser() {
        return DS().getActingUser();
      },
      // Prompt for the popup's "what support do you need?" flow. The Librarian
      // owns it so the "does this exist in the global db?" decision is grounded
      // in the actual tools registry (Datastore.global.tools) and conditioned
      // on the ability profile — not a hand-maintained vocabulary copy.
      // Fast lane: builds a string, never calls the LLM itself.
      async interpretNeedsPrompt(text) {
        const tools = DS().global.tools();
        const profile = await getOrInitProfile();
        const profileBlock = profile.supportAreas.length || profile.freeText ? `

What we know about this user:
- Support areas: ${profile.supportAreas.join(", ") || "unspecified"}` + (profile.freeText ? `
- In their words: "${profile.freeText}"` : "") : "";
        return `You are an accessibility assistant for a browser extension. The user describes what they need in plain language. Map their description to specific extension settings.

Available settings (use these exact keys):
${tools.settingsVocabularyLines().join("\n")}

Built-in tools these settings belong to (for context on what already exists):
${tools.forPrompt().map((t) => `- ${t.name}: ${t.description}`).join("\n")}${profileBlock}

Site categories (for scoping): ${TAX().categoryIds().join(", ")}.

User says: "${text}"

Return ONLY valid JSON with:
{
  "summary": "One friendly sentence describing what you understood",
  "scope": "Where these settings should apply. Use 'general' for everywhere (the default). If the user limits it to a kind of site, use 'category:<id>' with one of the categories above (e.g. 'on news sites' -> 'category:news', 'when watching videos' -> 'category:video'). If they name a specific website, use 'origin:<hostname>' (e.g. 'on youtube.com'). Only narrow the scope when the user explicitly limits it.",
  "settings": { /* only keys that should change, with their values */ },
  "reasons": { /* same keys as settings, each with a short reason why */ },
  "newSkills": [ /* ONLY if the user's need CANNOT be fully met by the settings and built-in tools above, suggest custom skills to build. Each object has "name" (short) and "description" (1-2 sentences of what it would do). Leave as empty array [] if existing settings are sufficient. */ ]
}`;
      },
      // The single entry point for observations — and the privacy floor.
      // Drops (never logs) when globally paused, when the origin is paused,
      // or when the origin's category is a no-memory zone without an explicit
      // opt-in. The log is the pipeline's WAL: extraction consumes entries
      // behind a cursor, so a crash mid-extraction loses nothing.
      async logObservation(obs) {
        const profile = await getOrInitProfile();
        if (profile.memoryPaused) return { logged: false, reason: "paused" };
        let origin = obs.origin || originOf(obs.url || "");
        let category = obs.category || null;
        if (origin) {
          const idx = await DS().get("mine.siteIndex");
          const entry = idx[origin];
          if (entry?.paused) return { logged: false, reason: "origin-paused" };
          category = category || entry?.category || TAX().categoryForHost(origin);
          if (category && TAX().noMemoryCategories().includes(category) && !entry?.memoryOptIn) {
            return { logged: false, reason: "no-memory-zone" };
          }
        }
        const WEIGHTS = { "setting-change": 3, "profile-applied": 3, "saved-action": 3, onboarding: 3, "agent-task": 2 };
        await DS().patch("mine.episodicLog", (log) => {
          const lastId = log.entries.length ? log.entries[log.entries.length - 1].id : 0;
          const id = Math.max(lastId, log.cursor) + 1;
          log.entries.push({
            id,
            t: clock.now(),
            type: obs.type || "observation",
            weight: obs.weight || WEIGHTS[obs.type] || 1,
            origin: origin || null,
            category: category || null,
            data: obs.data || {},
            text: String(obs.text || "").slice(0, 400)
          });
          if (log.entries.length > 500) log.entries.splice(0, log.entries.length - 500);
          return log;
        });
        scheduleExtraction();
        if (demo.isOn() && obs.type === "agent-task") {
          if (!origin) origin = "youtube.com";
          if (!category) category = "video";
        }
        const taskSucceeded = obs.data?.success || demo.isOn() && obs.type === "agent-task";
        if (obs.type === "agent-task" && taskSucceeded && origin && category) {
          demo.trace("skill", "reusable_q", "common reusable task?");
          try {
            await this._maybeProposeReusableAction(obs, origin, category);
          } catch (e) {
            console.warn("[Librarian] reusable-action proposal failed:", e.message);
          }
        }
        return { logged: true };
      },
      async _maybeProposeReusableAction(obs, origin, category) {
        const task = obs.data && obs.data.task || "";
        if (!task) return;
        const profiles = await DS().get("mine.profiles") || [];
        const exists = profiles.some((p) => p.siteTypes?.includes(category) && (p.actions || []).some((a) => (a.prompt || "").trim().toLowerCase() === task.trim().toLowerCase()));
        if (exists && !demo.isOn()) return;
        const profile = await getOrInitProfile();
        const suppressions = await DS().get("mine.suppressions");
        const shortTask = task.length > 60 ? task.slice(0, 57) + "\u2026" : task;
        await this._draftProposals([{
          // Category-level aspect: "don't suggest this" silences automation
          // suggestions for this site category, not just this one task.
          aspect: `reusable-action.category:${category}`,
          aspectLabel: `running "${shortTask}" automatically on ${category} sites`,
          change: {
            op: "add-profile-action",
            siteTypes: [category],
            action: { name: shortTask, prompt: task }
          },
          rationale: `You just had the agent do this on ${origin}. I can do it automatically whenever you visit a ${category} site.`,
          evidence: []
        }], { suppressions, profile, now: clock.now() });
        demo.trace("skill", "reusable_q", "proposed: save as skill");
        await updateBadge();
      },
      async setMemoryPaused(paused) {
        await DS().patch("mine.profile", (p) => {
          p = p || structuredClone(PROFILE_DEFAULTS);
          p.memoryPaused = !!paused;
          p.updatedAt = clock.now();
          return p;
        });
      },
      async setOriginPaused(origin, paused) {
        origin = (origin || "").toLowerCase().replace(/^www\./, "");
        await DS().patch("mine.siteIndex", (cur) => {
          cur[origin] = { ...cur[origin] || {}, paused: !!paused };
          return cur;
        });
      },
      // accept | declineOnce | suppress. Graduated consent: "not now" is a
      // 30-day cooldown; two soft declines escalate the NEXT proposal on this
      // aspect to offer permanent suppression; "suppress" writes a durable,
      // user-visible suppression record (a preference in its own right).
      async respondToProposal(id, response) {
        const props = await DS().get("mine.proposals");
        const prop = props.find((p) => p.id === id);
        if (!prop || prop.status !== "pending") return { ok: false, reason: "not-pending" };
        const now = clock.now();
        if (response === "accept") {
          prop.status = "accepted";
          if (prop.change?.op === "profile-set") {
            await this.setProfileField(prop.change.path, prop.change.value);
          } else if (prop.change?.op === "add-profile-action" && prop.change.action) {
            const siteTypes = prop.change.siteTypes || [];
            await DS().patch("mine.profiles", (profiles) => {
              profiles = profiles || [];
              let target = profiles.find((p) => p.autoApply && p.siteTypes?.some((t) => siteTypes.includes(t)));
              if (!target) {
                target = {
                  id: "profile-" + now,
                  name: `${siteTypes[0] ? siteTypes[0][0].toUpperCase() + siteTypes[0].slice(1) : "Auto"} automations`,
                  siteTypes,
                  autoApply: true,
                  settings: {},
                  actions: []
                };
                profiles.push(target);
              }
              if (!target.actions) target.actions = [];
              target.actions.push({
                id: "action-" + now,
                name: prop.change.action.name,
                prompt: prop.change.action.prompt,
                savedAt: now
              });
              return profiles;
            });
            demo.trace("skill", "skillsdb", "saved as skill.md");
            demo.trace("skill", "autoenable", "skill stored");
            demo.trace("skill", "profiledb_skill", "trigger registered");
            demo.trace("personal", "continual", "continual update");
          } else if (prop.change?.op === "add-memory" && prop.change.record) {
            const rec = normalizeRecord({ ...prop.change.record, source: "accepted-proposal", confidence: 0.95 }, now);
            await DS().patch("mine.profile", (p) => p);
            const shard = await DS().getMemoryShard(rec.scope);
            shard.push(rec);
            await DS().setMemoryShard(rec.scope, shard);
          } else if (prop.change?.op === "grant-request") {
            const { appId, appLabel, scopes } = prop.change;
            await DS().patch("mine.grants", (grants) => {
              grants = (grants || []).filter((g) => g.appId !== appId);
              grants.push(normalizeGrant({ id: newId("grant"), appId, appLabel, scopes, grantedAt: now }));
              return grants;
            });
          }
          for (const evId of prop.evidence || []) {
            const shards = await DS().allMemoryShards();
            for (const [scope, recs] of Object.entries(shards)) {
              const r = (recs || []).find((x) => x.id === evId);
              if (r) {
                r.confidence = Math.min(1, (r.confidence ?? 0.7) + 0.1);
                r.lastConfirmedAt = now;
                await DS().setMemoryShard(scope, recs);
              }
            }
          }
        } else if (response === "declineOnce") {
          prop.status = "declined";
          await DS().patch("mine.suppressions", (s) => {
            const existing = s.find((x) => x.aspect === prop.aspect && x.mode === "cooldown");
            if (existing) {
              existing.until = now + 30 * 24 * 3600 * 1e3;
              existing.declineCount = (existing.declineCount || 1) + 1;
            } else {
              s.push({ id: newId("sup"), aspect: prop.aspect, mode: "cooldown", until: now + 30 * 24 * 3600 * 1e3, declineCount: 1, createdAt: now });
            }
            return s;
          });
        } else if (response === "suppress") {
          prop.status = "suppressed";
          await DS().patch("mine.suppressions", (s) => {
            s = s.filter((x) => x.aspect !== prop.aspect);
            s.push({
              id: newId("sup"),
              aspect: prop.aspect,
              mode: "permanent",
              text: `Don't suggest changes about: ${prop.aspectLabel || prop.aspect}`,
              source: "explicit-user",
              createdAt: now
            });
            return s;
          });
        } else {
          return { ok: false, reason: "bad-response" };
        }
        prop.respondedAt = now;
        await DS().set("mine.proposals", props);
        await updateBadge();
        return { ok: true, status: prop.status };
      },
      // ====================== SLOW LANE (LLM) ======================
      // Drain the episodic log behind the cursor: one Gemini call extracts
      // candidate facts AND gates them against existing same-scope memories,
      // returning ADD/UPDATE/SUPERSEDE/NOOP operations plus profile-tier
      // proposal drafts. Idempotent: cursor advances only after ops apply.
      async extract() {
        if (!_gemini) return { ran: false, reason: "no-llm" };
        const log = await DS().get("mine.episodicLog");
        const pending = log.entries.filter((e) => e.id > log.cursor);
        if (!pending.length) return { ran: false, reason: "empty" };
        const lastId = pending[pending.length - 1].id;
        const scopes = /* @__PURE__ */ new Set(["general"]);
        for (const e of pending) {
          if (e.category) scopes.add(`category:${e.category}`);
          if (e.origin) scopes.add(`origin:${e.origin}`);
        }
        const existing = [];
        for (const s of scopes) {
          for (const r of await DS().getMemoryShard(s)) {
            if (r.status === "active") existing.push({ id: r.id, scope: s, text: r.text, settings: r.settings, occurrenceCount: r.occurrenceCount });
          }
        }
        const suppressions = await DS().get("mine.suppressions");
        const now = clock.now();
        const activeSuppressed = suppressions.filter((s) => s.mode === "permanent" || s.mode === "cooldown" && s.until > now).map((s) => s.aspect);
        const profile = await getOrInitProfile();
        const prompt = `You maintain the memory of a browser accessibility assistant. Convert raw observations into durable memory operations.

## Setting keys and their EXACT units/ranges (use these units in every "settings" object)
${DS().global.tools().settingsVocabularyLines().join("\n")}

## User profile
${JSON.stringify({ supportAreas: profile.supportAreas, freeText: profile.freeText }, null, 1)}

## New observations (weight 3 = deliberate user action, 1 = ambient)
${JSON.stringify(pending.map((e) => ({ type: e.type, weight: e.weight, origin: e.origin, category: e.category, text: e.text, data: e.data })), null, 1)}

## Existing memories (compare candidates against these)
${JSON.stringify(existing, null, 1)}

## Suppressed aspects (NEVER propose about these)
${JSON.stringify(activeSuppressed)}

Rules:
- Extract only durable, useful facts: preferences, repeated patterns, how-to knowledge. Ignore one-off low-weight noise (a single weight-1 event is exploration, not preference).
- scope: "general" | "category:<${TAX().categoryIds().join("|")}>" | "origin:<hostname>" | "context:<video|form|document>". Prefer the narrowest scope the evidence supports.
- For each candidate, compare to existing memories: same fact \u2192 {"op":"NOOP","id":<existing id>} (we bump its count); refines/strengthens \u2192 {"op":"UPDATE","id":...,"text":...,"settings":...}; CONFIDENTLY contradicts and should replace \u2192 {"op":"SUPERSEDE","id":...,"record":{...}}; the user did the OPPOSITE of an inferred record but you are NOT sure it's permanent \u2192 {"op":"CONTRADICT","id":<existing id>} (lowers its confidence, no replacement); genuinely new \u2192 {"op":"ADD","record":{...}}.
- record fields: text (one plain sentence), tier ("preference"|"site"|"task"), scope, kind ("preference"|"procedural"), importance 1-10, confidence 0-1, decayClass ("stable"|"slow"|"fast"), settings (object of extension setting keys like fontScale/darkMode/autoCaptions if directly actionable, else null).
- Changes to the user's ABILITY PROFILE (their disability/needs themselves, not site preferences) must NOT be memory records. Emit them under "proposals" instead: {aspect:"profile.<field>", aspectLabel:"plain words", change:{op:"profile-set",path:"fields.<field>",value:...}, rationale:"<1 plain sentence why>", evidence:[]}. Only propose when evidence is strong and repeated.
- Return ONLY JSON: {"operations":[...], "proposals":[...]}`;
        let parsed;
        try {
          parsed = parseJsonLoose(await _gemini(prompt));
        } catch (e) {
          console.warn("[Librarian] extract LLM call failed:", e.message);
          return { ran: false, reason: e.message };
        }
        if (!parsed) return { ran: false, reason: "unparseable" };
        const evidenceIds = pending.map((e) => e.id);
        const applied = { ADD: 0, UPDATE: 0, SUPERSEDE: 0, NOOP: 0, CONTRADICT: 0 };
        for (const op of parsed.operations || []) {
          try {
            if (op.op === "ADD" && op.record) {
              const rec = normalizeRecord({ ...op.record, evidence: evidenceIds }, now);
              const shard = await DS().getMemoryShard(rec.scope);
              shard.push(rec);
              await DS().setMemoryShard(rec.scope, shard);
              applied.ADD++;
            } else if ((op.op === "UPDATE" || op.op === "NOOP" || op.op === "SUPERSEDE" || op.op === "CONTRADICT") && op.id) {
              const target = existing.find((x) => x.id === op.id);
              if (!target) continue;
              const shard = await DS().getMemoryShard(target.scope);
              const r = shard.find((x) => x.id === op.id);
              if (!r) continue;
              if (op.op === "NOOP") {
                r.occurrenceCount = (r.occurrenceCount || 1) + 1;
                r.lastConfirmedAt = now;
                r.evidence = [.../* @__PURE__ */ new Set([...r.evidence || [], ...evidenceIds])].slice(-20);
                r.updatedAt = now;
              } else if (op.op === "UPDATE") {
                if (op.text) r.text = String(op.text).slice(0, 500);
                if (op.settings && typeof op.settings === "object") r.settings = sanitizeSettings(op.settings);
                r.occurrenceCount = (r.occurrenceCount || 1) + 1;
                r.confidence = Math.min(1, (r.confidence ?? 0.7) + 0.05);
                r.lastConfirmedAt = now;
                r.evidence = [.../* @__PURE__ */ new Set([...r.evidence || [], ...evidenceIds])].slice(-20);
                r.updatedAt = now;
              } else if (op.op === "CONTRADICT") {
                r.confidence = Math.max(0, (r.confidence ?? 0.7) - 0.2);
                r.updatedAt = now;
              } else if (op.op === "SUPERSEDE" && op.record) {
                if (r.strength === "floor") {
                  r.confidence = Math.max(0, (r.confidence ?? 0.7) - 0.2);
                  r.updatedAt = now;
                } else {
                  const rec = normalizeRecord({ ...op.record, evidence: evidenceIds }, now);
                  r.status = "superseded";
                  r.supersededBy = rec.id;
                  r.updatedAt = now;
                  const destShard = rec.scope === target.scope ? shard : await DS().getMemoryShard(rec.scope);
                  destShard.push(rec);
                  if (rec.scope !== target.scope) await DS().setMemoryShard(rec.scope, destShard);
                }
              }
              await DS().setMemoryShard(target.scope, shard);
              applied[op.op]++;
            }
          } catch (e) {
            console.warn("[Librarian] op apply failed:", e.message);
          }
        }
        await this._draftProposals(parsed.proposals || [], { suppressions, profile, now });
        await DS().patch("mine.episodicLog", (l) => {
          l.cursor = Math.max(l.cursor, lastId);
          return l;
        });
        await updateBadge();
        return { ran: true, applied, observations: pending.length };
      },
      // Gate + persist proposal drafts: suppression/cooldown filter, weekly
      // cap from metaPreferences, dedup against pending, plain-language pass
      // when the profile asks for it.
      async _draftProposals(drafts, { suppressions, profile, now }) {
        if (!drafts.length) return;
        const demoOn = demo.isOn();
        const props = await DS().get("mine.proposals");
        const weekAgo = now - 7 * 24 * 3600 * 1e3;
        let weekCount = props.filter((p) => p.createdAt > weekAgo).length;
        const cap = demoOn ? Infinity : profile.metaPreferences?.maxProposalsPerWeek ?? 3;
        for (const d of drafts) {
          if (!d.aspect || !d.change) continue;
          if (weekCount >= cap) break;
          const sup = demoOn ? null : suppressions.find((s) => s.aspect === d.aspect && (s.mode === "permanent" || s.until > now));
          if (sup) continue;
          if (props.some((p) => p.status === "pending" && p.aspect === d.aspect)) continue;
          props.push({
            id: newId("prop"),
            aspect: d.aspect,
            aspectLabel: d.aspectLabel || d.aspect,
            change: d.change,
            rationale: String(d.rationale || "").slice(0, 300),
            evidence: d.evidence || [],
            status: "pending",
            createdAt: now,
            respondedAt: null
          });
          weekCount++;
        }
        await DS().set("mine.proposals", props);
      },
      // Daily consolidation. Deterministic where possible; LLM only for the
      // category playbooks. Idempotent — safe to re-run.
      async reflect() {
        const now = clock.now();
        const shards = await DS().allMemoryShards();
        const idx = await DS().get("mine.siteIndex");
        const bySettingAndCat = {};
        for (const [scope, recs] of Object.entries(shards)) {
          if (!scope.startsWith("origin:")) continue;
          const origin = scope.slice("origin:".length);
          const cat = idx[origin]?.category || TAX().categoryForHost(origin);
          if (!cat) continue;
          for (const r of recs) {
            if (r.status !== "active" || !r.settings) continue;
            for (const [k, v] of Object.entries(r.settings)) {
              const key = `${cat}|${k}|${JSON.stringify(v)}`;
              (bySettingAndCat[key] = bySettingAndCat[key] || []).push({ scope, record: r, cat, k, v });
            }
          }
        }
        let promoted = 0;
        for (const group of Object.values(bySettingAndCat)) {
          const distinctOrigins = new Set(group.map((g) => g.scope));
          if (distinctOrigins.size < 3) continue;
          const { cat, k, v } = group[0];
          const catScope = `category:${cat}`;
          const catShard = await DS().getMemoryShard(catScope);
          if (catShard.some((r) => r.status === "active" && r.settings && JSON.stringify(r.settings[k]) === JSON.stringify(v))) continue;
          const rec = normalizeRecord({
            text: `Prefers ${k} = ${JSON.stringify(v)} on ${cat} sites (seen on ${distinctOrigins.size} sites)`,
            tier: "preference",
            scope: catScope,
            kind: "preference",
            importance: 6,
            confidence: 0.85,
            decayClass: "slow",
            settings: { [k]: v },
            source: "reflection-promotion",
            occurrenceCount: group.length,
            // Transitive grounding: a promoted category fact inherits the episodic
            // evidence of the origin records it consolidates, so its lineage to raw
            // observations survives even after those origin copies are superseded.
            evidence: [...new Set(group.flatMap((g) => g.record.evidence || []))].slice(-20)
          }, now);
          catShard.push(rec);
          await DS().setMemoryShard(catScope, catShard);
          for (const g of group) {
            const shard = await DS().getMemoryShard(g.scope);
            const r = shard.find((x) => x.id === g.record.id);
            if (r) {
              r.status = "superseded";
              r.supersededBy = rec.id;
              r.updatedAt = now;
            }
            await DS().setMemoryShard(g.scope, shard);
          }
          promoted++;
        }
        let expired = 0, purged = 0;
        for (const [scope, recs] of Object.entries(shards)) {
          let dirty = false;
          const kept = [];
          for (const r of await DS().getMemoryShard(scope)) {
            if (r.status === "active" && r.tier === "task" && now - (r.updatedAt || r.createdAt) > DECAY_HALF_LIFE.fast * 2) {
              r.status = "expired";
              r.updatedAt = now;
              dirty = true;
              expired++;
            }
            if ((r.status === "superseded" || r.status === "expired") && now - r.updatedAt > 30 * 24 * 3600 * 1e3) {
              purged++;
              dirty = true;
              continue;
            }
            kept.push(r);
          }
          if (dirty) await DS().setMemoryShard(scope, kept);
        }
        await DS().patch("mine.proposals", (props) => {
          for (const p of props) {
            if (p.status === "pending" && now - p.createdAt > 14 * 24 * 3600 * 1e3) p.status = "expired";
          }
          return props;
        });
        const profile = await getOrInitProfile();
        const generalShard = await DS().getMemoryShard("general");
        const topGeneral = generalShard.filter((r) => r.status === "active").sort((a, b) => scoreRecord(b, now) - scoreRecord(a, now)).slice(0, 6);
        const coreLines = [
          `Support areas: ${profile.supportAreas.join(", ") || "not specified"}.`,
          profile.freeText ? `In their words: ${profile.freeText}` : null,
          ...topGeneral.map((r) => `- ${r.text}`)
        ].filter(Boolean);
        const views = await DS().get("mine.views");
        views.coreBlock = coreLines.join("\n");
        views.playbooks = views.playbooks || {};
        if (_gemini) {
          for (const cat of TAX().categoryIds()) {
            const recs = (await DS().getMemoryShard(`category:${cat}`)).filter((r) => r.status === "active");
            if (recs.length < 3) continue;
            try {
              const md = await _gemini(
                `Write a short markdown playbook (max 120 words, plain language) for helping this user on ${cat} websites, based on these memories:
` + recs.map((r) => `- ${r.text}`).join("\n") + `
User support areas: ${profile.supportAreas.join(", ")}. Output only the playbook markdown.`
              );
              if (md) views.playbooks[cat] = md.trim().slice(0, 1500);
            } catch {
            }
          }
        }
        const summaryShards = await DS().allMemoryShards();
        const activeRecs = [];
        for (const [scope, recs] of Object.entries(summaryShards)) {
          for (const r of recs || []) {
            if (r.status === "active") activeRecs.push({ ...r, _scope: scope });
          }
        }
        const classCounts = { episodic: 0, semantic: 0, procedural: 0 };
        const settingTally = {};
        const categoriesAdapted = /* @__PURE__ */ new Set();
        for (const r of activeRecs) {
          classCounts[memoryClassOf(r)]++;
          if (r._scope.startsWith("category:")) categoriesAdapted.add(r._scope.slice("category:".length));
          for (const [k, v] of Object.entries(r.settings || {})) {
            settingTally[k] = settingTally[k] || {};
            const vk = JSON.stringify(v);
            settingTally[k][vk] = (settingTally[k][vk] || 0) + 1;
          }
        }
        const topSettings = Object.entries(settingTally).map(([key, vals]) => {
          const [vk, count] = Object.entries(vals).sort((a, b) => b[1] - a[1])[0];
          return { key, value: JSON.parse(vk), count };
        }).sort((a, b) => b.count - a.count).slice(0, 8);
        const reflectLog = await DS().get("mine.episodicLog");
        const pendingObs = reflectLog.entries.filter((e) => e.id > reflectLog.cursor).length;
        const summaryLines = [
          `Tracking ${activeRecs.length} consolidated ${activeRecs.length === 1 ? "memory" : "memories"} (${classCounts.semantic} preference, ${classCounts.procedural} how-to)` + (pendingObs ? `; ${pendingObs} new observation${pendingObs === 1 ? "" : "s"} awaiting consolidation.` : ".")
        ];
        if (topSettings.length) {
          summaryLines.push("Most consistent adaptations:");
          for (const s of topSettings) summaryLines.push(`- ${s.key} = ${JSON.stringify(s.value)} (${s.count}\xD7)`);
        }
        if (categoriesAdapted.size) {
          summaryLines.push(`Site-specific adaptations on: ${[...categoriesAdapted].sort().join(", ")}.`);
        }
        views.behaviorSummary = {
          text: summaryLines.join("\n"),
          counts: { ...classCounts, pendingObservations: pendingObs },
          topSettings,
          categories: [...categoriesAdapted].sort(),
          renderedAt: now
        };
        views.renderedAt = now;
        await DS().set("mine.views", views);
        for (const scope of Object.keys(shards)) {
          const recs = await DS().getMemoryShard(scope);
          const ids = new Set(recs.map((r) => r.id));
          let dirty = false;
          for (const r of recs) {
            if (r.supersededBy && !ids.has(r.supersededBy)) {
              r.supersededBy = null;
              dirty = true;
            }
          }
          if (dirty) await DS().setMemoryShard(scope, recs);
        }
        const cited = /* @__PURE__ */ new Set();
        const freshShards = await DS().allMemoryShards();
        for (const recs of Object.values(freshShards)) {
          for (const r of recs || []) {
            if (r.status === "active" && Array.isArray(r.evidence)) {
              for (const id of r.evidence) cited.add(id);
            }
          }
        }
        const grace = DECAY_HALF_LIFE.fast;
        let discarded = 0;
        await DS().patch("mine.episodicLog", (log) => {
          const before = log.entries.length;
          log.entries = log.entries.filter((e) => e.id > log.cursor || cited.has(e.id) || now - e.t < grace);
          discarded = before - log.entries.length;
          return log;
        });
        await updateBadge();
        return { ran: true, promoted, expired, purged, discarded };
      }
    };
    function scheduleExtraction() {
      scheduler.debounce("aaLibrarianExtract", 2e4, () => {
        Librarian.extract().catch((e) => console.warn("[Librarian] extract failed:", e.message));
      });
    }
    async function updateBadge() {
      try {
        const pending = await Librarian.listProposals("pending");
        await consent.notifyPending(pending.length);
      } catch {
      }
    }
    scheduler.every("aaLibrarianExtract", 30, () => {
      Librarian.extract().catch((e) => console.warn("[Librarian] extract failed:", e.message));
    });
    scheduler.every("aaLibrarianReflect", 60 * 24, () => {
      Librarian.reflect().catch((e) => console.warn("[Librarian] reflect failed:", e.message));
    });
    return Librarian;
  }

  // ../toolkit/adapters/chrome/ports.js
  function chromeClock() {
    return { now: () => Date.now() };
  }
  function chromeScheduler() {
    const handlers = /* @__PURE__ */ new Map();
    const timers = /* @__PURE__ */ new Map();
    let listenerInstalled = false;
    function ensureListener() {
      if (listenerInstalled) return;
      if (!(chrome.alarms && chrome.alarms.onAlarm)) return;
      chrome.alarms.onAlarm.addListener((alarm) => {
        const fn = handlers.get(alarm.name);
        if (fn) fn();
      });
      listenerInstalled = true;
    }
    return {
      every(id, periodMinutes, handler) {
        handlers.set(id, handler);
        ensureListener();
        if (chrome.alarms) chrome.alarms.create(id, { periodInMinutes: periodMinutes });
      },
      debounce(id, delayMs, handler) {
        const prev = timers.get(id);
        if (prev) clearTimeout(prev);
        timers.set(id, setTimeout(() => {
          timers.delete(id);
          handler();
        }, delayMs));
      }
    };
  }
  function chromeConsent() {
    return {
      async notifyPending(count) {
        try {
          await chrome.action.setBadgeText({ text: count ? String(count) : "" });
          if (count) await chrome.action.setBadgeBackgroundColor({ color: "#1a73e8" });
        } catch {
        }
      }
    };
  }
  function chromeDemo() {
    return {
      isOn: () => !!globalThis.AA_DEMO_MODE,
      trace: (diagram, region, label) => {
        try {
          if (globalThis.aaDemoTrace) globalThis.aaDemoTrace(diagram, region, label);
        } catch {
        }
      }
    };
  }

  // ../toolkit/adapters/chrome/librarian.entry.js
  if (!globalThis.Librarian) {
    globalThis.Librarian = createLibrarian({
      datastore: globalThis.Datastore,
      taxonomy: globalThis.AA_TAXONOMY,
      clock: chromeClock(),
      scheduler: chromeScheduler(),
      consent: chromeConsent(),
      demo: chromeDemo()
    });
  }
})();
