// Chrome adapter — datastore. Bundled by personalized-extension/build.js to
// extension/lib/datastore.js (classic script). Wires chrome.storage behind
// the Areas port and assigns globalThis.Datastore, exactly as the
// pre-toolkit file did. Loaded after taxonomy.js / tools-registry.js.
import { createDatastore } from '../../core/datastore.js';

// chrome.storage area → toolkit StorageArea port (promise-based, single key)
function wrapArea(storageArea) {
  return {
    get(key, def) {
      return new Promise((resolve) => {
        storageArea.get(key, (data) => {
          const v = data ? data[key] : undefined;
          resolve(v === undefined ? def : v);
        });
      });
    },
    set(key, value) {
      return new Promise((resolve, reject) => {
        storageArea.set({ [key]: value }, () => {
          if (chrome.runtime.lastError) reject(new Error(chrome.runtime.lastError.message));
          else resolve();
        });
      });
    },
  };
}

globalThis.Datastore = createDatastore({
  areas: {
    local: wrapArea(chrome.storage.local),
    sync: wrapArea(chrome.storage.sync),
  },
  // Global tier reads the classic-script globals so load order and consumers
  // stay identical (tools-registry.js / skills-db.js generated by build.js).
  globalTier: {
    tools: () => globalThis.AA_TOOLS || null,
    taxonomy: () => globalThis.AA_TAXONOMY || null,
    skills: () => globalThis.AA_SKILLS || [],
  },
  clock: { now: () => Date.now() },
});
