const esbuild = require('esbuild');
const path = require('path');
const fs = require('fs');

const isWatch = process.argv.includes('--watch');

// ---------------------------------------------------------------------------
// Browser-harness skills manifest
// ---------------------------------------------------------------------------
// browser-harness-orig/ holds bundled markdown knowledge files (interaction
// patterns + per-site playbooks). Service-worker fetch can resolve them via
// chrome.runtime.getURL but cannot list directories, so we pre-bake an index
// at build time. Change BH_ORIG_PATH in one place if the directory is renamed
// or the python files are stripped out — the runtime path constant in
// extension/browser-harness/skills.js mirrors this.
const BH_ORIG_PATH = 'extension/browser-harness/browser-harness-orig';
const BH_INTERACTION_SUBPATH = 'interaction-skills';
const BH_DOMAIN_SUBPATH = 'agent-workspace/domain-skills';
const BH_MANIFEST_OUT = 'extension/browser-harness/skills-manifest.json';

function listMd(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => f.replace(/\.md$/, ''))
    .sort();
}

function buildSkillsManifest() {
  const interactionDir = path.resolve(__dirname, BH_ORIG_PATH, BH_INTERACTION_SUBPATH);
  const domainDir = path.resolve(__dirname, BH_ORIG_PATH, BH_DOMAIN_SUBPATH);
  const interaction = listMd(interactionDir);
  // Manifest entry: { dir: <on-disk name>, files: [...] }. Lookup key is the
  // lowercased dir name so a normalized hostname like "boss-zhipin" still
  // resolves the upstream "BOSS-zhipin" folder without renaming the tree.
  const domain = {};
  if (fs.existsSync(domainDir)) {
    for (const dirName of fs.readdirSync(domainDir).sort()) {
      const hdir = path.join(domainDir, dirName);
      try {
        if (!fs.statSync(hdir).isDirectory()) continue;
      } catch { continue; }
      const files = listMd(hdir);
      if (files.length) {
        const key = dirName.toLowerCase();
        domain[key] = { dir: dirName, files };
      }
    }
  }
  fs.mkdirSync(path.dirname(path.resolve(__dirname, BH_MANIFEST_OUT)), { recursive: true });
  fs.writeFileSync(
    path.resolve(__dirname, BH_MANIFEST_OUT),
    JSON.stringify({ interaction, domain }, null, 2)
  );
  console.log(
    `skills-manifest.json: ${interaction.length} interaction skills, ${Object.keys(domain).length} domain hosts`
  );
}

// ---------------------------------------------------------------------------
// Built-in tools registry (global Tools db)
// ---------------------------------------------------------------------------
// skills/registry.js is the canonical ESM source (node-side consumers import
// it directly). Extension pages and the background SW can't load ES modules,
// so we bake the registry into a classic script that assigns
// globalThis.AA_TOOLS — same pattern as skills-manifest.json above.
const TOOLS_REGISTRY_OUT = 'extension/lib/tools-registry.js';

async function buildToolsRegistry() {
  const { skillRegistry, settingsMeta } = await import('./skills/registry.js');
  const out = `// GENERATED by build.js from skills/registry.js — do not edit by hand.
// Canonical source: personalized-extension/skills/registry.js
// Loaded by background.js (importScripts) and extension pages (script tag).
globalThis.AA_TOOLS = {
  version: 1,
  list: ${JSON.stringify(skillRegistry, null, 2)},
  settingsMeta: ${JSON.stringify(settingsMeta, null, 2)},
  // One prompt-ready line per setting: "key (type...): description".
  settingsVocabularyLines() {
    return Object.entries(this.settingsMeta).map(([k, m]) => {
      let t = m.type;
      if (m.type === 'number' && m.range) t = \`number \${m.range[0]}-\${m.range[1]}\`;
      if (m.type === 'enum' && m.options) t = 'string: ' + m.options.map(o => '"' + o + '"').join(', ');
      return \`- \${k} (\${t}): \${m.description}\`;
    });
  },
  byId(id) { return this.list.find(s => s.id === id) || null; },
  byArea(area) { return this.list.filter(s => s.supportAreas.includes(area)); },
  // chrome.storage.sync settings activated by enabling each of \`ids\`.
  settingsFor(ids) {
    const merged = {};
    for (const id of ids || []) {
      const t = this.byId(id);
      if (t && t.settings) Object.assign(merged, t.settings);
    }
    return merged;
  },
  forPrompt() {
    return this.list.map(s => ({
      id: s.id, name: s.name, description: s.description,
      supportAreas: s.supportAreas, siteRelevance: s.siteRelevance,
    }));
  },
};
`;
  const outPath = path.resolve(__dirname, TOOLS_REGISTRY_OUT);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
  console.log(`tools-registry.js: ${skillRegistry.length} built-in tools`);
}

const contentConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/content/content.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/content/content.bundle.js'),
  format: 'iife',
  target: 'chrome110',
  // Minified: this bundle is injected into EVERY page (<all_urls>); parse cost
  // matters. Sourcemap retained for debugging. (Review finding #11.)
  minify: true,
  sourcemap: true,
  logLevel: 'info',
  // colorjs.io /fn sub-path imports (used by utils/color.js → fix-contrast.js)
  // are not exported by colorjs.io 0.7.0's package.json "exports" map; mark
  // them external so the bundle uses the top-level 'colorjs.io/fn' entry that
  // IS exported. The content script never directly imports these sub-paths.
  external: [
    'colorjs.io/fn/spaces/*',
    'colorjs.io/fn/contrast/*',
  ],
};

// Browser-harness primitives. Loaded into the service worker by background.js
// via self.importScripts -- so the bundle must be a classic script (IIFE),
// not an ES module. The entry assigns the public surface onto
// globalThis.BrowserHarness; all internal modules under src/harness/ stay
// invisible to the rest of the SW.
const harnessConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/browser-harness/src/harness/index.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/browser-harness/dist/harness.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: false,
  logLevel: 'info',
  // .bhinject files are real JS authored as standalone in-page scripts; the
  // text loader inlines them as string constants so the harness can hand
  // them to Runtime.evaluate without a build-time string concatenation.
  loader: { '.bhinject': 'text' },
};

// Agent loop. Same constraints as harnessConfig; assigns onto
// globalThis.BrowserAgent. Depends on globalThis.BrowserHarness +
// globalThis.BrowserSkills being populated already (background.js's
// importScripts order guarantees this).
const agentConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/browser-harness/src/agent/index.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/browser-harness/dist/agent.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: false,
  logLevel: 'info',
};

// Voice offscreen document. Hosts the Gemini Live WebSocket + audio capture/
// playback (Web APIs unavailable in the SW). Loaded by offscreen.html, which
// the SW spawns via chrome.offscreen.createDocument.
const offscreenConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/offscreen/src/index.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/offscreen/offscreen.bundle.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: false,
  logLevel: 'info',
};

// Voice side-panel UI. Pure presentation layer; no Live API calls happen
// here. Connects to the offscreen doc via chrome.runtime messages routed
// through the SW.
const sidepanelConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/sidepanel/src/index.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/sidepanel/sidepanel.bundle.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: false,
  logLevel: 'info',
};

// ---------------------------------------------------------------------------
// Toolkit core (portable personal-memory engine) → classic-script globals
// ---------------------------------------------------------------------------
// The reference implementation lives in /toolkit (ES modules, platform-
// agnostic, port-injected). The service worker (importScripts) and the popup
// (<script>) load classic scripts that assign globalThis.AA_TAXONOMY /
// Datastore / Librarian, so each chrome adapter entry is bundled to an IIFE --
// same pattern as harness.js / agent.js / tools-registry.js. Edit the source
// under /toolkit; lib/{taxonomy,datastore,librarian}.js are generated.
const TOOLKIT_CHROME = path.resolve(__dirname, '..', 'toolkit', 'adapters', 'chrome');
const TOOLKIT_BANNER = '// GENERATED by build.js from /toolkit (ES module source). Do not edit by hand.';

function toolkitConfig(entry, outName) {
  return {
    entryPoints: [path.resolve(TOOLKIT_CHROME, entry)],
    bundle: true,
    outfile: path.resolve(__dirname, 'extension/lib', outName),
    format: 'iife',
    target: 'chrome110',
    sourcemap: false,
    logLevel: 'info',
    banner: { js: TOOLKIT_BANNER },
  };
}

const taxonomyConfig = toolkitConfig('taxonomy.entry.js', 'taxonomy.js');
const datastoreConfig = toolkitConfig('datastore.entry.js', 'datastore.js');
const librarianConfig = toolkitConfig('librarian.entry.js', 'librarian.js');
const webSurfaceConfig = toolkitConfig('web-surface.entry.js', 'web-surface.js');

// ---------------------------------------------------------------------------
// aria-query build-time tables
// ---------------------------------------------------------------------------
// Generates utils/aria-tables.gen.js (valid ARIA roles minus abstract + valid
// aria-* attribute names) from the aria-query package so wcag-fixes.js and
// constants.js never hand-roll these lists.
const ARIA_TABLES_OUT = 'utils/aria-tables.gen.js';

function buildAriaTables() {
  const aq = require('aria-query');
  // Roles: iterate the Map to find non-abstract ones.
  const concreteRoles = [];
  aq.roles.forEach((def, name) => {
    if (!def.abstract) concreteRoles.push(name);
  });
  concreteRoles.sort();

  // ARIA attribute names.
  const ariaProps = [];
  aq.aria.forEach((_def, name) => ariaProps.push(name));
  ariaProps.sort();

  const out =
    '// GENERATED by build.js from aria-query — do not edit by hand.\n' +
    '// Source: personalized-extension/build.js buildAriaTables()\n' +
    '// Re-generate: npm run build\n\n' +
    `export const VALID_ARIA_ROLES = new Set(${JSON.stringify(concreteRoles, null, 2)});\n\n` +
    `export const VALID_ARIA_ATTRS = new Set(${JSON.stringify(ariaProps, null, 2)});\n`;

  const outPath = path.resolve(__dirname, ARIA_TABLES_OUT);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
  console.log(`aria-tables.gen.js: ${concreteRoles.length} concrete roles, ${ariaProps.length} aria attrs`);
}

// ---------------------------------------------------------------------------
// axe-core asset copy
// ---------------------------------------------------------------------------
// Copies node_modules/axe-core/axe.min.js into extension/lib/ so the SW can
// inject it with chrome.scripting.executeScript({ files: ['lib/axe.min.js'] }).
const AXE_SRC = 'node_modules/axe-core/axe.min.js';
const AXE_DST = 'extension/lib/axe.min.js';

function copyAxe() {
  const src = path.resolve(__dirname, AXE_SRC);
  const dst = path.resolve(__dirname, AXE_DST);
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
  const size = Math.round(fs.statSync(dst).size / 1024);
  console.log(`axe.min.js copied (${size} kB) → extension/lib/axe.min.js`);
}

async function build() {
  buildSkillsManifest();
  buildAriaTables();
  copyAxe();
  await buildToolsRegistry();
  if (isWatch) {
    const ctxs = await Promise.all([
      esbuild.context(contentConfig),
      esbuild.context(harnessConfig),
      esbuild.context(agentConfig),
      esbuild.context(offscreenConfig),
      esbuild.context(sidepanelConfig),
      esbuild.context(taxonomyConfig),
      esbuild.context(datastoreConfig),
      esbuild.context(librarianConfig),
      esbuild.context(webSurfaceConfig),
    ]);
    await Promise.all(ctxs.map((c) => c.watch()));
    console.log('Watching for changes...');
  } else {
    await Promise.all([
      esbuild.build(contentConfig),
      esbuild.build(harnessConfig),
      esbuild.build(agentConfig),
      esbuild.build(offscreenConfig),
      esbuild.build(sidepanelConfig),
      esbuild.build(taxonomyConfig),
      esbuild.build(datastoreConfig),
      esbuild.build(librarianConfig),
      esbuild.build(webSurfaceConfig),
    ]);
    console.log('Build complete.');
  }
}

build().catch((e) => {
  console.error(e);
  process.exit(1);
});
