const esbuild = require('esbuild');
const path = require('path');
const fs = require('fs');

const isWatch = process.argv.includes('--watch');

// ---------------------------------------------------------------------------
// Browser-harness skills manifest
// ---------------------------------------------------------------------------
// browser-harness-orig/ holds bundled markdown knowledge files (interaction
// patterns + per-site playbooks). Service-worker fetch can resolve them via
// chrome.runtime.getURL but cannot list directories, so we pre-bake an index
// at build time. Change BH_ORIG_PATH in one place if the directory is renamed
// or the python files are stripped out — the runtime path constant in
// extension/browser-harness/skills.js mirrors this.
const BH_ORIG_PATH = 'extension/browser-harness/browser-harness-orig';
const BH_INTERACTION_SUBPATH = 'interaction-skills';
const BH_DOMAIN_SUBPATH = 'agent-workspace/domain-skills';
const BH_MANIFEST_OUT = 'extension/browser-harness/skills-manifest.json';

function listMd(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => f.replace(/\.md$/, ''))
    .sort();
}

function buildSkillsManifest() {
  const interactionDir = path.resolve(__dirname, BH_ORIG_PATH, BH_INTERACTION_SUBPATH);
  const domainDir = path.resolve(__dirname, BH_ORIG_PATH, BH_DOMAIN_SUBPATH);
  const interaction = listMd(interactionDir);
  // Manifest entry: { dir: <on-disk name>, files: [...] }. Lookup key is the
  // lowercased dir name so a normalized hostname like "boss-zhipin" still
  // resolves the upstream "BOSS-zhipin" folder without renaming the tree.
  const domain = {};
  if (fs.existsSync(domainDir)) {
    for (const dirName of fs.readdirSync(domainDir).sort()) {
      const hdir = path.join(domainDir, dirName);
      try {
        if (!fs.statSync(hdir).isDirectory()) continue;
      } catch { continue; }
      const files = listMd(hdir);
      if (files.length) {
        const key = dirName.toLowerCase();
        domain[key] = { dir: dirName, files };
      }
    }
  }
  fs.mkdirSync(path.dirname(path.resolve(__dirname, BH_MANIFEST_OUT)), { recursive: true });
  fs.writeFileSync(
    path.resolve(__dirname, BH_MANIFEST_OUT),
    JSON.stringify({ interaction, domain }, null, 2)
  );
  console.log(
    `skills-manifest.json: ${interaction.length} interaction skills, ${Object.keys(domain).length} domain hosts`
  );
}

// ---------------------------------------------------------------------------
// Built-in tools registry (global Tools db)
// ---------------------------------------------------------------------------
// skills/registry.js is the canonical ESM source (node-side consumers import
// it directly). Extension pages and the background SW can't load ES modules,
// so we bake the registry into a classic script that assigns
// globalThis.AA_TOOLS — same pattern as skills-manifest.json above.
const TOOLS_REGISTRY_OUT = 'extension/lib/tools-registry.js';

async function buildToolsRegistry() {
  const { skillRegistry, settingsMeta } = await import('./skills/registry.js');
  const out = `// GENERATED by build.js from skills/registry.js — do not edit by hand.
// Canonical source: personalized-extension/skills/registry.js
// Loaded by background.js (importScripts) and extension pages (script tag).
globalThis.AA_TOOLS = {
  version: 1,
  list: ${JSON.stringify(skillRegistry, null, 2)},
  settingsMeta: ${JSON.stringify(settingsMeta, null, 2)},
  // One prompt-ready line per setting: "key (type...): description".
  settingsVocabularyLines() {
    return Object.entries(this.settingsMeta).map(([k, m]) => {
      let t = m.type;
      if (m.type === 'number' && m.range) t = \`number \${m.range[0]}-\${m.range[1]}\`;
      if (m.type === 'enum' && m.options) t = 'string: ' + m.options.map(o => '"' + o + '"').join(', ');
      return \`- \${k} (\${t}): \${m.description}\`;
    });
  },
  byId(id) { return this.list.find(s => s.id === id) || null; },
  byArea(area) { return this.list.filter(s => s.supportAreas.includes(area)); },
  // chrome.storage.sync settings activated by enabling each of \`ids\`.
  settingsFor(ids) {
    const merged = {};
    for (const id of ids || []) {
      const t = this.byId(id);
      if (t && t.settings) Object.assign(merged, t.settings);
    }
    return merged;
  },
  forPrompt() {
    return this.list.map(s => ({
      id: s.id, name: s.name, description: s.description,
      supportAreas: s.supportAreas, siteRelevance: s.siteRelevance,
    }));
  },
};
`;
  const outPath = path.resolve(__dirname, TOOLS_REGISTRY_OUT);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
  console.log(`tools-registry.js: ${skillRegistry.length} built-in tools`);
}

// ---------------------------------------------------------------------------
// Built-in skills (global "Skills db")
// ---------------------------------------------------------------------------
// Canonical source: the SKILL.md playbooks in toolkit/skills/builtin/. Parsed
// with the toolkit's own parseSkill and baked into a classic script assigning
// globalThis.AA_SKILLS (parsed Skill objects), so the SW and pages get the
// built-in skills without loading ES modules or reading files at runtime.
const SKILLS_SRC_DIR = path.resolve(__dirname, '..', 'toolkit', 'skills', 'builtin');
const SKILLS_DB_OUT = 'extension/lib/skills-db.js';

async function buildSkillsDb() {
  const { parseSkill } = await import('../toolkit/core/skill.js');
  const skills = [];
  if (fs.existsSync(SKILLS_SRC_DIR)) {
    for (const f of fs.readdirSync(SKILLS_SRC_DIR).filter(n => n.endsWith('.md')).sort()) {
      skills.push(parseSkill(fs.readFileSync(path.join(SKILLS_SRC_DIR, f), 'utf8')));
    }
  }
  const out = `// GENERATED by build.js from toolkit/skills/builtin/*.md — do not edit by hand.
// Built-in "Skills db": SKILL.md playbooks parsed to Skill objects.
// Loaded by background.js (importScripts); read via Datastore.global.skills().
globalThis.AA_SKILLS = ${JSON.stringify(skills, null, 2)};
`;
  const outPath = path.resolve(__dirname, SKILLS_DB_OUT);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
  console.log(`skills-db.js: ${skills.length} built-in skills`);
}

const contentConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/content/content.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/content/content.bundle.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: true,
  logLevel: 'info',
};

// ---------------------------------------------------------------------------
// Toolkit core (Librarian / Datastore / taxonomy)
// ---------------------------------------------------------------------------
// The platform-agnostic source of truth lives in the top-level toolkit/
// (toolkit/core + toolkit/adapters/chrome — see toolkit/README.md). These
// bundles bake the chrome adapter entries into the classic scripts that
// background.js importScripts and popup.html script-tags at the SAME paths
// as before the extraction, so no consumer changed. Do not edit the
// extension/lib outputs by hand.
const TOOLKIT_DIR = path.resolve(__dirname, '..', 'toolkit');

function toolkitConfig(entry, outfile) {
  return {
    entryPoints: [path.join(TOOLKIT_DIR, 'adapters', 'chrome', entry)],
    bundle: true,
    outfile: path.resolve(__dirname, outfile),
    format: 'iife',
    target: 'chrome110',
    sourcemap: false,
    logLevel: 'info',
    banner: { js: `// GENERATED by build.js from toolkit/ — do not edit by hand.\n// Canonical source: toolkit/core + toolkit/adapters/chrome/${entry}` },
  };
}

const toolkitTaxonomyConfig = toolkitConfig('taxonomy.entry.js', 'extension/lib/taxonomy.js');
const toolkitDatastoreConfig = toolkitConfig('datastore.entry.js', 'extension/lib/datastore.js');
const toolkitLibrarianConfig = toolkitConfig('librarian.entry.js', 'extension/lib/librarian.js');

// Browser-harness primitives. Loaded into the service worker by background.js
// via self.importScripts -- so the bundle must be a classic script (IIFE),
// not an ES module. The entry assigns the public surface onto
// globalThis.BrowserHarness; all internal modules under src/harness/ stay
// invisible to the rest of the SW.
const harnessConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/browser-harness/src/harness/index.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/browser-harness/dist/harness.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: false,
  logLevel: 'info',
  // .bhinject files are real JS authored as standalone in-page scripts; the
  // text loader inlines them as string constants so the harness can hand
  // them to Runtime.evaluate without a build-time string concatenation.
  loader: { '.bhinject': 'text' },
};

// Agent loop. Same constraints as harnessConfig; assigns onto
// globalThis.BrowserAgent. Depends on globalThis.BrowserHarness +
// globalThis.BrowserSkills being populated already (background.js's
// importScripts order guarantees this).
const agentConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/browser-harness/src/agent/index.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/browser-harness/dist/agent.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: false,
  logLevel: 'info',
};

// Voice offscreen document. Hosts the Gemini Live WebSocket + audio capture/
// playback (Web APIs unavailable in the SW). Loaded by offscreen.html, which
// the SW spawns via chrome.offscreen.createDocument.
const offscreenConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/offscreen/src/index.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/offscreen/offscreen.bundle.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: false,
  logLevel: 'info',
};

// Voice side-panel UI. Pure presentation layer; no Live API calls happen
// here. Connects to the offscreen doc via chrome.runtime messages routed
// through the SW.
const sidepanelConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/sidepanel/src/index.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/sidepanel/sidepanel.bundle.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: false,
  logLevel: 'info',
};

async function build() {
  buildSkillsManifest();
  await buildToolsRegistry();
  await buildSkillsDb();
  if (isWatch) {
    const ctxs = await Promise.all([
      esbuild.context(contentConfig),
      esbuild.context(harnessConfig),
      esbuild.context(agentConfig),
      esbuild.context(offscreenConfig),
      esbuild.context(sidepanelConfig),
      esbuild.context(toolkitTaxonomyConfig),
      esbuild.context(toolkitDatastoreConfig),
      esbuild.context(toolkitLibrarianConfig),
    ]);
    await Promise.all(ctxs.map((c) => c.watch()));
    console.log('Watching for changes...');
  } else {
    await Promise.all([
      esbuild.build(contentConfig),
      esbuild.build(harnessConfig),
      esbuild.build(agentConfig),
      esbuild.build(offscreenConfig),
      esbuild.build(sidepanelConfig),
      esbuild.build(toolkitTaxonomyConfig),
      esbuild.build(toolkitDatastoreConfig),
      esbuild.build(toolkitLibrarianConfig),
    ]);
    console.log('Build complete.');
  }
}

build().catch((e) => {
  console.error(e);
  process.exit(1);
});
