"""Paths, exit statuses, session state, and the loaders for the page scripts.

Bottom layer of the engine package: this module imports nothing from its
siblings, and every other module in the package may import from it. Nothing
here opens a browser or calls a model, so it stays cheap to import.
"""

import json
import sys
import urllib.request
from pathlib import Path

import os as _os


# Every JavaScript asset the engine loads lives in cli/, one directory above
# this package. The second `.parent` is what walks out of cli/ai4a11y/ and
# into cli/, so do not remove it: the assets stay where the npm build and the
# packaging patterns already put them, and two of the loaders below answer a
# missing file with an empty string rather than an error, so a wrong path here
# would show up as "could not inject tools" long after the fact.
_CLI_DIR = Path(__file__).resolve().parent.parent

# Output directory for screenshots / filmstrips. Override with AI4A11Y_OUT env var.
OUT = Path(_os.environ.get('AI4A11Y_OUT') or (Path.home() / 'Downloads' / 'ai4a11y'))
OUT.mkdir(parents=True, exist_ok=True)

# CLI tools bundle path (generated by npm run build:cli)
_CLI_TOOLS_BUNDLE = _CLI_DIR / "cli-tools.bundle.js"
_CLI_TOOLS_SCRIPT = None

# Readability library (for ReaderMode), vendored under cli/lib/ so the CLI
# does not depend on the extension repository's tree
_READABILITY_PATH = _CLI_DIR / "lib" / "readability.js"
_READABILITY_SCRIPT = None

# The page scripts this engine hands to page.evaluate. They live in cli/js/ so
# an editor treats them as JavaScript and a diff that touches a page query
# reads as a JavaScript change. `_js` is the lowest thing in the package: it
# reads a path and nothing else, so every other layer can sit on top of it.
_JS_DIR = _CLI_DIR / "js"
_JS_CACHE = {}


def _js(name):
    """Read a JavaScript file from cli/js/, cached after the first read.

    A missing file raises. The two older loaders in this module return an empty
    string instead, which is why a package built without its JavaScript assets
    reports "Could not inject tools" rather than naming the file it could not
    find.
    """
    if name not in _JS_CACHE:
        path = _JS_DIR / name
        if not path.exists():
            raise FileNotFoundError(
                f"ai4a11y is missing its script {name}. Expected it at {path}. "
                "This usually means the package was built without its JavaScript "
                "assets."
            )
        _JS_CACHE[name] = path.read_text(encoding="utf-8")
    return _JS_CACHE[name]


# ============================================================
# Output helpers
#
# A command and its caller share one stdout, so a command that can be asked
# for --json has to choose between the payload and the human rendering rather
# than write both. Sixteen commands made that choice by hand, and a progress
# line that escaped the choice left the payload unparseable for the caller.
#
# These two sit at the top of the file, above every command, because they read
# nothing but their arguments and `json`. The fix engine calls `quiet` for its
# own progress, and a later split of this module puts that engine in a lower
# layer than the commands, so `quiet` has to live below both of them.
# ============================================================

def quiet(json_output):
    """print, or a no-op when a machine is reading stdout.

    Progress lines and the payload share stdout, so under --json the progress
    has to be silenced or the payload does not parse.
    """
    return (lambda *a, **k: None) if json_output else print


def emit(payload, render, json_output):
    """Print the JSON payload, or run the human rendering. Never both."""
    if json_output:
        print(json.dumps(payload, indent=2))
    else:
        render()


def warn(*args):
    """Write a diagnostic to stderr.

    A command that could not run at all still owed its caller a clean stdout,
    and said so there anyway: under --json the message landed in front of the
    payload, so the document did not parse, and when the command produced no
    payload the caller parsed prose instead of an answer. Stderr is where this
    belongs whether or not --json was asked for, because it is not the answer
    to the question the command was asked.
    """
    print(*args, file=sys.stderr, flush=True)


def _get_readability_script():
    """Load the Readability library for ReaderMode."""
    global _READABILITY_SCRIPT
    if _READABILITY_SCRIPT is None:
        if _READABILITY_PATH.exists():
            _READABILITY_SCRIPT = _READABILITY_PATH.read_text()
        else:
            _READABILITY_SCRIPT = ""
    return _READABILITY_SCRIPT


# Session state file for persistent profile settings
_SESSION_STATE_FILE = OUT / ".ai4a11y_session_state.json"


def _get_session_state():
    """Load persistent session state (active profile, tool settings)."""
    if _SESSION_STATE_FILE.exists():
        try:
            return json.loads(_SESSION_STATE_FILE.read_text())
        except:
            pass
    return {}


def _save_session_state(state):
    """Save persistent session state."""
    _SESSION_STATE_FILE.write_text(json.dumps(state, indent=2))


def _get_active_profile():
    """Get the currently active profile name."""
    return _get_session_state().get('activeProfile')


def _set_active_profile(profile_name):
    """Set the active profile (persists across commands)."""
    state = _get_session_state()
    state['activeProfile'] = profile_name
    _save_session_state(state)


def _get_cli_tools_script():
    """Load the CLI tools bundle (adapters + profiles) for injection."""
    global _CLI_TOOLS_SCRIPT
    if _CLI_TOOLS_SCRIPT is None:
        if _CLI_TOOLS_BUNDLE.exists():
            _CLI_TOOLS_SCRIPT = _CLI_TOOLS_BUNDLE.read_text()
        else:
            warn(f"Warning: CLI tools bundle not found at {_CLI_TOOLS_BUNDLE}")
            warn("Run 'npm run build:cli' to generate it.")
            _CLI_TOOLS_SCRIPT = ""
    return _CLI_TOOLS_SCRIPT


# Model selection is centralized so a future model bump is a one-line change.
# Grounding is a constrained classification ('pick N from list'); vision reasons
# over a screenshot. Per CLAUDE.md: Sonnet floor, Opus when possible.
_IRIS_GROUND_MODEL = "claude-sonnet-5"     # text-only grounding from a11y candidates
_IRIS_VISION_MODEL = "claude-opus-4-8"     # screenshot reasoning (describe / ask / visual tap)
# ai4a11y wants fast, grounded vision descriptions — not deep multi-step reasoning.
# --effort low tells Opus 4.7 to skip extended thinking; keeps latency predictable.
_IRIS_VISION_EFFORT = "low"


# Exit status for a command that could not reach a model for at least one of
# the items it was asked to fix. Kept distinct from 1 so a script can tell
# "install the Claude Code CLI" from a real error.
AI_UNAVAILABLE_EXIT = 3

# Exit status for a command that stopped because the recorded session no longer
# names the browser it started.
SESSION_MISMATCH_EXIT = 4

# Exit status for a session command run before any session was started.
NO_SESSION_EXIT = 5

# Printed in place of a fix whenever the model was unreachable for that item.
NEEDS_AI_LINE = "needs-ai: no answer from the Claude Code CLI, nothing written"


# Session state location, CDP port, and browser profile dir. Overridable via
# environment so tests and parallel sessions can isolate themselves.
SESSION_DIR = Path(_os.environ.get("AI4A11Y_HOME") or (Path.home() / ".ai4a11y"))
SESSION_FILE = SESSION_DIR / "session.json"
CDP_PORT = int(_os.environ.get("AI4A11Y_CDP_PORT") or 9222)
USER_DATA_DIR = _os.environ.get("AI4A11Y_USER_DATA_DIR") or "/tmp/ai4a11y-user-data"


# Path to bundled axe-core
_AXE_BUNDLE_PATH = _CLI_DIR / "axe-core.min.js"
_AXE_CDN = "https://cdnjs.cloudflare.com/ajax/libs/axe-core/4.12.1/axe.min.js"
_AXE_SCRIPT = None


def _get_axe_script():
    """Load axe-core script (cached). Downloads from CDN if local bundle missing."""
    global _AXE_SCRIPT
    if _AXE_SCRIPT is None:
        if _AXE_BUNDLE_PATH.exists():
            _AXE_SCRIPT = _AXE_BUNDLE_PATH.read_text()
        else:
            print("(downloading axe-core...)", flush=True)
            with urllib.request.urlopen(_AXE_CDN, timeout=10) as resp:
                _AXE_SCRIPT = resp.read().decode('utf-8')
            _AXE_BUNDLE_PATH.write_text(_AXE_SCRIPT)
    return _AXE_SCRIPT
